Repository saleor/saleor-dashboard, pull requests merged in 2021-10, with the labels that each got.

#1379 tests for warehouses in checkout
  cypress/elements/warehouses/warehouse-details.js
  cypress/integration/checkout/warehouses.js
  cypress/integration/configuration/warehouse.js
  cypress/support/api/requests/Checkout.js
  cypress/support/api/requests/Warehouse.js
  cypress/support/pages/warehousePage.js
Labels: run e2e

#1471 Fix wrong words and ordering for staff member form (#1424)
  locale/defaultMessages.json
  src/components/AppStatus/AppStatus.tsx
  src/components/AppStatus/index.ts
  src/staff/components/StaffDetailsPage/StaffDetailsPage.tsx
  src/staff/components/StaffDetailsPage/messages.ts
  src/staff/components/UserStatus/UserStatus.tsx
  src/staff/components/UserStatus/index.ts
  src/staff/components/UserStatus/messages.ts
Labels: 3.1, reviewed

#1470 Refactor Translations Page (#1451)
  locale/defaultMessages.json
  src/translations/components/TranslationsAttributesPage/TranslationsAttributesPage.tsx
  src/translations/components/TranslationsAttributesPage/messages.ts
  src/translations/utils.ts
Labels: reviewed
