Repository saleor/saleor-dashboard, pull requests merged in 2021-09, with the labels that each got.

#1351 Check onBlur existance before calling it
  src/components/SingleAutocompleteSelectField/SingleAutocompleteSelectField.tsx
Labels: 3.1, reviewed

#1352 Fix hidden link section in Menu Item modal
  src/navigation/components/MenuItemDialog/MenuItemDialog.tsx
Labels: 3.1, reviewed

#1354 Enforce category selection in product creator (#1337)
  src/products/components/ProductCreatePage/form.tsx
Labels: 3.1, reviewed

#1266 Skip empty navigation searches
  src/hooks/makeSearch.ts
Labels: 3.0, 3.1

#1302 fix failing tests
  cypress/apiRequests/Attribute.js
  cypress/apiRequests/Channels.js
  cypress/apiRequests/Order.js
  cypress/elements/channels/add-channel-form-selectors.js
  cypress/elements/shared/sharedElements.js
  cypress/integration/categories.js
  cypress/integration/configuration/attributes/filters.js
  cypress/integration/configuration/channels.js
  cypress/integration/configuration/shippingMethods/channelsInShipping.js
  cypress/integration/orders/channelsInDraftOrders.js
  cypress/integration/orders/draftOrders.js
  cypress/integration/orders/orders.js
  cypress/integration/products/productsList/filteringProducts.js
  cypress/integration/products/productsVariants.js
  cypress/integration/staffMembers.js
  cypress/steps/attributesSteps.js
  cypress/steps/catalog/products/VariantsSteps.js
  cypress/steps/catalog/products/productSteps.js
  cypress/steps/categoriesSteps.js
  cypress/steps/channelsSteps.js
  cypress/steps/permissions.js
  cypress/steps/shared/selects.js
  cypress/steps/shared/tables.js
  cypress/steps/shippingMethodSteps.js
  cypress/steps/user.js
  cypress/support/format/formatCurrencyAmount.js
Labels: run e2e

#1377 Hiding channel picker on simple product edit page
  src/products/views/ProductUpdate/ProductUpdate.tsx
Labels: 3.0

#1375 Fix draft order incorrect label
  locale/defaultMessages.json
  src/orders/components/OrderDraftDetailsSummary/OrderDraftDetailsSummary.tsx
  src/orders/components/OrderDraftDetailsSummary/messages.ts
Labels: 3.0

#1384 Fix draft order incorrect label
  locale/defaultMessages.json
  src/orders/components/OrderDraftDetailsSummary/OrderDraftDetailsSummary.tsx
  src/orders/components/OrderDraftDetailsSummary/messages.ts
Labels: 3.1, reviewed

#1381 channel picker hidden on simple products
  src/products/views/ProductUpdate/ProductUpdate.tsx
Labels: 3.1, reviewed

#1416 Add Demo Banner
  CHANGELOG.md
  locale/defaultMessages.json
  package-lock.json
  package.json
  src/components/DemoBanner/DemoBanner.tsx
  src/components/DemoBanner/constants.ts
  src/components/DemoBanner/index.ts
  src/components/DemoBanner/styles.ts
  src/index.tsx
Labels: 3.1, reviewed

#1401 Fix initial list settings
  package-lock.json
  package.json
  src/apps/views/AppsList/AppsList.tsx
  src/auth/hooks/useExternalAuthProvider.ts
  src/auth/hooks/useSaleorAuthProvider.ts
  src/hooks/useListSettings.test.ts
  src/hooks/useListSettings.ts
  src/hooks/useLocalStorage.test.ts
  src/hooks/useLocalStorage.ts
Labels: reviewed

#1417 Fix back button on manage channels at product details (#1380)
  src/channels/ChannelsWithVariantsAvailabilityCard/ChannelWithVariantAvailabilityItemWrapper.tsx
  src/channels/components/ChannelsWithVariantsAvailabilityDialog/ChannelsWithVariantsAvailabilityDialog.stories.tsx
  src/channels/components/ChannelsWithVariantsAvailabilityDialog/ChannelsWithVariantsAvailabilityDialog.tsx
  src/channels/components/ChannelsWithVariantsAvailabilityDialog/ChannelsWithVariantsAvailabilityDialogContent.tsx
  src/components/ActionDialog/ActionDialog.tsx
  src/products/views/ProductUpdate/ProductUpdate.tsx
  src/products/views/ProductUpdate/consts.ts
  src/products/views/ProductUpdate/types.ts
  src/products/views/ProductUpdate/useChannelVariantListings.ts
  src/products/views/ProductUpdate/useChannelsWithProductVariants.test.ts
  src/products/views/ProductUpdate/useChannelsWithProductVariants.ts
  src/products/views/ProductUpdate/utils.ts
Labels: reviewed

#1428 Fetch shop data after user is authenticated
  src/components/Shop/index.tsx
  src/components/Shop/query.ts
  src/components/Shop/types/ShopInfo.ts
  src/index.tsx
Labels: 3.0, reviewed

#1437 Add page type and attributes permissions handling
  cypress/Data/permissions.js
  cypress/Data/permissionsUsers.js
  src/auth/components/SectionRoute.tsx
  src/auth/misc.ts
  src/components/AppLayout/menuStructure.ts
  src/configuration/ConfigurationPage.tsx
  src/configuration/index.tsx
  src/configuration/utils.ts
  src/index.tsx
Labels: 3.0, reviewed

#1447 Add margin to notification box
  src/components/messages/styles.ts
Labels: reviewed

#1297 add badges and tooltips for deleted products
  assets/images/error.svg
  assets/images/warning.svg
  cypress/elements/orders/order-refund.js
  locale/defaultMessages.json
  src/components/StatusBadge/StatusBadge.tsx
  src/components/StatusBadge/index.ts
  src/components/TableCellAvatar/Avatar.tsx
  src/fragments/orders.ts
  src/fragments/types/RefundOrderLineFragment.ts
  src/orders/components/OrderDraftDetailsProducts/TableLine.tsx
  src/orders/components/OrderDraftDetailsProducts/messages.ts
  src/orders/components/OrderFulfillPage/OrderFulfillPage.tsx
  src/orders/components/OrderFulfilledProductsCard/OrderFulfilledProductsCard.tsx
  src/orders/components/OrderProductsCardElements/OrderProductsTableRow.tsx
  src/orders/components/OrderProductsCardElements/messages.ts
  src/orders/components/OrderRefundFulfilledProducts/OrderRefundFulfilledProducts.tsx
  src/orders/components/OrderRefundFulfilledProducts/messages.ts
  src/orders/components/OrderRefundPage/fixtures.ts
  src/orders/components/OrderRefundUnfulfilledProducts/OrderRefundUnfulfilledProducts.tsx
  src/orders/components/OrderRefundUnfulfilledProducts/messages.ts
  src/orders/components/OrderReturnPage/OrderReturnPage.tsx
  src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ReturnItemsCard.tsx
  src/orders/components/OrderReturnPage/messages.ts
  src/orders/components/OrderUnfulfilledProductsCard/OrderUnfulfilledProductsCard.tsx
  src/orders/components/OrderUnfulfilledProductsCard/messages.ts
  src/orders/types/OrderRefundData.ts
  src/orders/utils/data.test.ts
Labels: 3.0
