Repository saleor/saleor-dashboard, pull requests merged in 2021-08, with the labels that each got.

#1283 multiple item deletion parseqs fix
  src/apps/urls.ts
  src/attributes/urls.ts
  src/attributes/views/AttributeList/filters.test.ts
  src/auth/urls.ts
  src/categories/urls.ts
  src/channels/urls.ts
  src/collections/urls.ts
  src/collections/views/CollectionList/filters.test.ts
  src/customers/urls.ts
  src/customers/views/CustomerList/filters.test.ts
  src/discounts/urls.ts
  src/discounts/views/SaleList/filters.test.ts
  src/discounts/views/VoucherList/filters.test.ts
  src/hooks/usePaginator.ts
  src/navigation/urls.ts
  src/orders/urls.ts
  src/orders/views/OrderDraftList/filters.test.ts
  src/orders/views/OrderList/filters.test.ts
  src/pageTypes/urls.ts
  src/pages/urls.ts
  src/permissionGroups/urls.ts
  src/plugins/urls.ts
  src/plugins/views/PluginList/filters.test.ts
  src/productTypes/urls.ts
  src/productTypes/views/ProductTypeList/filters.test.ts
  src/products/views/ProductList/filters.test.ts
  src/shipping/urls.ts
  src/siteSettings/urls.ts
  src/staff/urls.ts
  src/staff/views/StaffList/filters.test.ts
  src/translations/urls.ts
  src/translations/views/TranslationsAttributes.tsx
  src/translations/views/TranslationsCategories.tsx
  src/translations/views/TranslationsCollections.tsx
  src/translations/views/TranslationsEntities.tsx
  src/translations/views/TranslationsPages.tsx
  src/translations/views/TranslationsProducts.tsx
  src/translations/views/TranslationsSales.tsx
  src/translations/views/TranslationsShippingMethod.tsx
  src/translations/views/TranslationsVouchers.tsx
  src/utils/urls.ts
  src/warehouses/urls.ts
  src/webhooks/urls.ts
Labels: run e2e

#1250 tests for filters
  cypress/apiRequests/Attribute.js
  cypress/apiRequests/Product.js
  cypress/elements/attribute/attributes_details.js
  cypress/elements/catalog/products/products-list.js
  cypress/elements/shared/sharedElements.js
  cypress/integration/categories.js
  cypress/integration/configuration/attributes/filters.js
  cypress/steps/attributesSteps.js
  cypress/steps/catalog/products/productsListSteps.js
  cypress/url/urlList.js
  cypress/utils/products/productsUtils.js
Labels: run e2e

#1303 Extend list of languages
  schema.graphql
  src/collections/types/CollectionList.ts
  src/types/globalTypes.ts
Labels: 3.0

#1311 fix dashboard crash when no channels exist
  src/components/AppLayout/AppLayout.tsx
Labels: reviewed

#1306 horizontal scroll fix
  package-lock.json
  package.json
  src/components/ResponsiveTable/ResponsiveTable.tsx
Labels: 3.0

#1313 Horizontal scroll fix on tables
  package-lock.json
  package.json
  src/components/ResponsiveTable/ResponsiveTable.tsx
Labels: reviewed

#1310 Extend list of languages
  schema.graphql
  src/types/globalTypes.ts
Labels: reviewed

#1316 Saleor 3611/3.0/warehouse settings card fix
  src/shipping/components/ShippingZoneSettingsCard/ShippingZoneSettingsCard.tsx
Labels: 3.0, reviewed

#1341 add fallback page title for nameless customers
  locale/defaultMessages.json
  src/customers/components/CustomerAddressListPage/CustomerAddressListPage.tsx
Labels: 3.0

#1346 fix dashboard crash when using the channel selector in product view
  src/channels/components/ChannelsWithVariantsAvailabilityDialog/ChannelsWithVariantsAvailabilityDialogContent.tsx
Labels: 3.1, reviewed

#1339 add app field to order details
  src/fragments/orders.ts
  src/fragments/types/OrderDetailsFragment.ts
  src/fragments/types/OrderEventFragment.ts
  src/orders/components/OrderHistory/OrderHistory.tsx
  src/orders/fixtures.ts
  src/orders/types/FulfillOrder.ts
  src/orders/types/OrderAddNote.ts
  src/orders/types/OrderCancel.ts
  src/orders/types/OrderCapture.ts
  src/orders/types/OrderConfirm.ts
  src/orders/types/OrderDetails.ts
  src/orders/types/OrderDiscountAdd.ts
  src/orders/types/OrderDiscountDelete.ts
  src/orders/types/OrderDiscountUpdate.ts
  src/orders/types/OrderDraftCancel.ts
  src/orders/types/OrderDraftFinalize.ts
  src/orders/types/OrderDraftUpdate.ts
  src/orders/types/OrderFulfillmentCancel.ts
  src/orders/types/OrderFulfillmentRefundProducts.ts
  src/orders/types/OrderFulfillmentUpdateTracking.ts
  src/orders/types/OrderLineDelete.ts
  src/orders/types/OrderLineDiscountRemove.ts
  src/orders/types/OrderLineDiscountUpdate.ts
  src/orders/types/OrderLineUpdate.ts
  src/orders/types/OrderLinesAdd.ts
  src/orders/types/OrderMarkAsPaid.ts
  src/orders/types/OrderRefund.ts
  src/orders/types/OrderShippingMethodUpdate.ts
  src/orders/types/OrderUpdate.ts
  src/orders/types/OrderVoid.ts
Labels: reviewed

#1348 prevent the creation of empty channel names
  src/channels/pages/ChannelDetailsPage/ChannelDetailsPage.tsx
Labels: 3.1, reviewed

#1347 fallback title for address books for customers with no name set
  locale/defaultMessages.json
  src/customers/components/CustomerAddressListPage/CustomerAddressListPage.tsx
Labels: 3.1, reviewed
