Repository saleor/saleor-dashboard, pull requests merged in 2021-11, with the labels that each got.

#1561 Add scrollable area for user addresses
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressEdit.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/styles.ts
Labels: 3.0

#1530 Disable save button in channel edit page when default country is not selected
  src/channels/pages/ChannelDetailsPage/ChannelDetailsPage.tsx
Labels: 3.0

#1552 Allow to create simple product with no channels
  src/products/views/ProductCreate/ProductCreate.tsx
Labels: 3.0

#1527 Fix assign products dialog covered search input
  src/shipping/components/ShippingMethodProductsAddDialog/ShippingMethodProductsAddDialog.tsx
Labels: 3.0

#1564 Add scrollable area for user addresses (#1561)
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressEdit.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/styles.ts
Labels: 3.1, reviewed

#1570 Add contentType prop to file attribute mutation
  src/attributes/types/AttributeOfUploadedFile.ts
  src/attributes/utils/data.ts
  src/attributes/utils/handlers.ts
Labels: 3.1, reviewed

#1574 Disable save button in channel edit page when default country is not selected (#1530)
  src/channels/pages/ChannelDetailsPage/ChannelDetailsPage.tsx
Labels: 3.1, reviewed

#1577 Fix assign products dialog covered search input (#1527)
  src/shipping/components/ShippingMethodProductsAddDialog/ShippingMethodProductsAddDialog.tsx
Labels: 3.1, reviewed

#1575 Allow to create simple product with no channels #1552
  src/products/views/ProductCreate/ProductCreate.tsx
Labels: 3.1, reviewed

#1581 Add sorting products by update at date
  locale/defaultMessages.json
  src/config.ts
  src/productTypes/types/ProductAttributeAssignmentUpdate.ts
  src/products/components/ProductList/ProductList.tsx
  src/products/components/ProductList/messages.ts
  src/products/components/ProductListPage/ProductListPage.tsx
  src/products/fixtures.ts
  src/products/queries.ts
  src/products/types/ProductList.ts
  src/products/urls.ts
  src/products/views/ProductList/sort.ts
Labels: 3.1

#1584 Add sorting products by update at date
  locale/defaultMessages.json
  src/config.ts
  src/products/components/ProductList/ProductList.tsx
  src/products/components/ProductList/messages.ts
  src/products/components/ProductListPage/ProductListPage.tsx
  src/products/fixtures.ts
  src/products/queries.ts
  src/products/types/ProductList.ts
  src/products/urls.ts
  src/products/views/ProductList/sort.ts
Labels: 3.0, reviewed

#1605 Use order token for metadata updates
  src/fragments/orders.ts
  src/fragments/types/OrderDetailsFragment.ts
  src/orders/fixtures.ts
  src/orders/types/FulfillOrder.ts
  src/orders/types/OrderCancel.ts
  src/orders/types/OrderCapture.ts
  src/orders/types/OrderConfirm.ts
  src/orders/types/OrderDetails.ts
  src/orders/types/OrderDiscountAdd.ts
  src/orders/types/OrderDiscountDelete.ts
  src/orders/types/OrderDiscountUpdate.ts
  src/orders/types/OrderDraftCancel.ts
  src/orders/types/OrderDraftFinalize.ts
  src/orders/types/OrderDraftUpdate.ts
  src/orders/types/OrderFulfillmentCancel.ts
  src/orders/types/OrderFulfillmentRefundProducts.ts
  src/orders/types/OrderFulfillmentUpdateTracking.ts
  src/orders/types/OrderLineDelete.ts
  src/orders/types/OrderLineDiscountRemove.ts
  src/orders/types/OrderLineDiscountUpdate.ts
  src/orders/types/OrderLineUpdate.ts
  src/orders/types/OrderLinesAdd.ts
  src/orders/types/OrderMarkAsPaid.ts
  src/orders/types/OrderRefund.ts
  src/orders/types/OrderShippingMethodUpdate.ts
  src/orders/types/OrderUpdate.ts
  src/orders/types/OrderVoid.ts
  src/orders/views/OrderDetails/index.tsx
Labels: 3.0, reviewed

#1572 Allow returning & refunding partially paid orders
  src/orders/components/OrderRefundReturnAmount/OrderRefundReturnAmount.tsx
Labels: 3.0

#1560 Fix partially cut checkboxes in channel dialogs
  src/channels/components/ChannelsWithVariantsAvailabilityDialog/ChannelsWithVariantsAvailabilityDialogContent.tsx
  src/components/ChannelsAvailabilityDialogWrapper/ChannelsAvailabilityDialogWrapper.tsx
  src/components/ControlledCheckbox.tsx
Labels: 3.0

#1608 Fix savebar hiding on short screens
  src/components/ChannelsAvailabilityDialogWrapper/ChannelsAvailabilityDialogWrapper.tsx
Labels: 3.1

#1609 Fix savebar hiding on short screens
  src/components/ChannelsAvailabilityDialogWrapper/ChannelsAvailabilityDialogWrapper.tsx
Labels: 3.0, reviewed

#1614 Add permissions to Catalog menu item
  src/components/AppLayout/menuStructure.ts
Labels: 3.1, reviewed

#1612 Allow returning & refunding partially paid orders (#1572)
  src/orders/components/OrderRefundReturnAmount/OrderRefundReturnAmount.tsx
Labels: 3.1, reviewed

#1613 Fix partially cut checkboxes in channel dialogs (#1560)
  src/channels/components/ChannelsWithVariantsAvailabilityDialog/ChannelsWithVariantsAvailabilityDialogContent.tsx
  src/components/ChannelsAvailabilityDialogWrapper/ChannelsAvailabilityDialogWrapper.tsx
  src/components/ControlledCheckbox.tsx
Labels: 3.1, reviewed

#1611 Fix assign countries dialogs
  src/components/Form/Form.tsx
  src/discounts/components/DiscountCountrySelectDialog/DiscountCountrySelectDialog.tsx
  src/discounts/components/DiscountCountrySelectDialog/styles.ts
  src/shipping/components/ShippingZoneCountriesAssignDialog/ShippingZoneCountriesAssignDialog.tsx
  src/shipping/components/ShippingZoneCountriesAssignDialog/styles.ts
  src/styles/useScrollableDialogStyle.ts
Labels: 3.0, reviewed

#1610 Fix assign countries dialogs
  src/components/Form/Form.tsx
  src/discounts/components/DiscountCountrySelectDialog/DiscountCountrySelectDialog.tsx
  src/discounts/components/DiscountCountrySelectDialog/styles.ts
  src/shipping/components/ShippingZoneCountriesAssignDialog/ShippingZoneCountriesAssignDialog.tsx
  src/shipping/components/ShippingZoneCountriesAssignDialog/styles.ts
  src/styles/useScrollableDialogStyle.ts
Labels: 3.1

#1602 Fix fulfillment of lines with not enough stock and no image
  src/orders/components/OrderFulfillStockExceededDialogLine/OrderFulfillStockExceededDialogLine.tsx
Labels: 3.0

#1622 Refactor sale update and create forms (#1553)
  src/channels/utils.ts
  src/discounts/components/SaleCreatePage/SaleCreatePage.tsx
  src/discounts/components/SaleDetailsPage/SaleDetailsPage.tsx
  src/discounts/components/SaleValue/SaleValue.tsx
  src/discounts/components/SaleValue/SaleValueTextField.tsx
  src/discounts/components/SaleValue/types.ts
  src/discounts/handlers.ts
  src/discounts/mutations.ts
  src/discounts/types/SaleUpdate.ts
  src/discounts/views/SaleCreate/SaleCreate.tsx
  src/discounts/views/SaleDetails/SaleDetails.tsx
  src/discounts/views/SaleDetails/handlers.ts
Labels: 3.1, reviewed

#1629 Add optional channel selection in price and weight rates view + voucher view
  src/discounts/views/VoucherDetails/VoucherDetails.tsx
  src/hooks/useChannels.test.ts
  src/shipping/views/PriceRatesCreate/PriceRatesCreate.tsx
  src/shipping/views/PriceRatesUpdate/PriceRatesUpdate.tsx
  src/shipping/views/WeightRatesCreate/WeightRatesCreate.tsx
  src/shipping/views/WeightRatesUpdate/WeightRatesUpdate.tsx
Labels: 3.0, reviewed

#1624 Fix saving initial variant attributes
  src/attributes/utils/data.ts
  src/products/utils/data.ts
Labels: 3.1

#1625 Fix saving initial variant attributes
  src/attributes/utils/data.ts
  src/products/utils/data.ts
Labels: 3.0, reviewed
