Repository saleor/saleor-dashboard, pull requests merged in 2021-12, with the labels that each got.

#1618 Searching addresses in order drafts
  locale/defaultMessages.json
  package-lock.json
  package.json
  src/customers/components/CustomerAddressChoiceCard/CustomerAddressChoiceCard.tsx
  src/customers/components/CustomerAddressChoiceCard/styles.ts
  src/intl.ts
  src/misc.ts
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressEdit.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesSearch.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/messages.ts
  src/orders/components/OrderCustomerAddressesEditDialog/styles.ts
  src/orders/components/OrderCustomerAddressesEditDialog/utils.ts
Labels: 3.0

#1649 Use node v14 for running tests on CI (#1646)
  .github/workflows/test.yml
  testUtils/intl.ts
Labels: 3.0, reviewed

#1655 Searching addresses in order drafts (#1618)
  locale/defaultMessages.json
  package-lock.json
  package.json
  src/customers/components/CustomerAddressChoiceCard/CustomerAddressChoiceCard.tsx
  src/customers/components/CustomerAddressChoiceCard/styles.ts
  src/intl.ts
  src/misc.ts
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressEdit.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesSearch.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/messages.ts
  src/orders/components/OrderCustomerAddressesEditDialog/styles.ts
  src/orders/components/OrderCustomerAddressesEditDialog/utils.ts
Labels: 3.1, reviewed

#1657 Fix state retention on outside modal click in address search
  package-lock.json
  package.json
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
Labels: 3.0

#1644 Fix auto scroll
  src/categories/index.tsx
  src/categories/urls.ts
  src/categories/views/CategoryDetails.tsx
  src/collections/urls.ts
  src/collections/views/CollectionDetails.tsx
  src/discounts/components/SaleDetailsPage/SaleDetailsPage.tsx
  src/discounts/components/VoucherDetailsPage/VoucherDetailsPage.tsx
  src/discounts/index.tsx
  src/discounts/urls.ts
  src/discounts/views/SaleDetails/SaleDetails.tsx
  src/discounts/views/VoucherDetails/VoucherDetails.tsx
  src/hooks/useLocalPaginator.ts
  src/hooks/useNavigator.ts
  src/hooks/usePaginator.ts
  src/shipping/urls.ts
  src/shipping/views/PriceRatesUpdate/PriceRatesUpdate.tsx
  src/shipping/views/ShippingZoneDetails/index.tsx
  src/shipping/views/WeightRatesUpdate/WeightRatesUpdate.tsx
Labels: 3.1

#1645 Fix auto scroll
  src/categories/index.tsx
  src/categories/urls.ts
  src/categories/views/CategoryDetails.tsx
  src/collections/urls.ts
  src/collections/views/CollectionDetails.tsx
  src/discounts/components/SaleDetailsPage/SaleDetailsPage.tsx
  src/discounts/components/VoucherDetailsPage/VoucherDetailsPage.tsx
  src/discounts/index.tsx
  src/discounts/urls.ts
  src/discounts/views/SaleDetails/SaleDetails.tsx
  src/discounts/views/VoucherDetails/VoucherDetails.tsx
  src/hooks/useLocalPaginator.ts
  src/hooks/useNavigator.ts
  src/hooks/usePaginator.ts
  src/shipping/urls.ts
  src/shipping/views/PriceRatesUpdate/PriceRatesUpdate.tsx
  src/shipping/views/ShippingZoneDetails/index.tsx
  src/shipping/views/WeightRatesUpdate/WeightRatesUpdate.tsx
Labels: 3.0, reviewed

#1652 Fix initial discount calculation on draft order line
  src/hooks/useUpdateEffect.ts
  src/orders/components/OrderDiscountCommonModal/OrderDiscountCommonModal.tsx
Labels: reviewed

#1639 Fix order fulfill warehouse filtering
  src/orders/components/OrderFulfillPage/OrderFulfillPage.tsx
  src/orders/components/OrderFulfillStockExceededDialog/styles.ts
  src/orders/views/OrderFulfill/OrderFulfill.tsx
Labels: 3.0

#1667 Add items response in updateMetadata mutation
  src/fragments/types/MetadataFragment.ts
  src/utils/metadata/types/UpdateMetadata.ts
  src/utils/metadata/types/UpdatePrivateMetadata.ts
  src/utils/metadata/updateMetadata.ts
Labels: 3.0

#1665 Fix attributeValueDelete mutation error - required first/last value
  src/attributes/utils/handlers.ts
Labels: 3.0

#1635 Separate sync and async app webhooks
  locale/defaultMessages.json
  schema.graphql
  src/types/globalTypes.ts
  src/webhooks/components/WebhookCreatePage/WebhookCreatePage.tsx
  src/webhooks/components/WebhookCreatePage/WebhooksCreatePage.stories.tsx
  src/webhooks/components/WebhookCreatePage/index.ts
  src/webhooks/components/WebhookDetailsPage/WebhookDetailsPage.stories.tsx
  src/webhooks/components/WebhookDetailsPage/WebhookDetailsPage.tsx
  src/webhooks/components/WebhookDetailsPage/index.ts
  src/webhooks/components/WebhookDetailsPage/messages.ts
  src/webhooks/components/WebhookEvents/WebhookEvents.tsx
  src/webhooks/components/WebhookEvents/messages.ts
  src/webhooks/components/WebhookInfo/WebhookInfo.tsx
  src/webhooks/components/WebhookInfo/messages.ts
  src/webhooks/components/WebhookStatus/WebhookStatus.tsx
  src/webhooks/components/WebhookStatus/messages.ts
  src/webhooks/components/WebhooksDetailsPage/WebhooksDetailsPage.stories.tsx
  src/webhooks/components/WebhooksDetailsPage/WebhooksDetailsPage.tsx
  src/webhooks/components/WebhooksDetailsPage/index.ts
  src/webhooks/fixtures.ts
  src/webhooks/handlers.ts
  src/webhooks/queries.ts
  src/webhooks/types/WebhookDetails.ts
  src/webhooks/utils.ts
  src/webhooks/views/WebhooksCreate.tsx
  src/webhooks/views/WebhooksDetails.tsx
Labels: 3.1, reviewed

#1679 Fix attributeValueDelete mutation error - required first/last value
  src/attributes/utils/handlers.ts
Labels: 3.1, reviewed

#1680 Add items response in updateMetadata mutation (#1667)
  src/utils/metadata/types/UpdateMetadata.ts
  src/utils/metadata/types/UpdatePrivateMetadata.ts
  src/utils/metadata/updateMetadata.ts
Labels: 3.1, reviewed

#1660 Fix error when clicked on filter if list is loading
  src/components/Filter/FilterContent/FilterContent.tsx
  src/components/Filter/FilterContent/FilterContentBody.tsx
  src/components/Filter/FilterContent/FilterContentBodyNameField.tsx
Labels: 3.0

#1676 Add tests for delete/update warehouse
  cypress/elements/shipping/shipping-zone-details.js
  cypress/integration/configuration/warehouses/warehouse.js
Labels: run e2e

#1681 Disable form change check in variant creation
  src/products/components/ProductVariantCreatePage/ProductVariantCreatePage.tsx
Labels: 3.1

#1682 Disable form change check in variant creation
  src/products/components/ProductVariantCreatePage/ProductVariantCreatePage.tsx
Labels: 3.0

#1686 Fix modal footer shadow issue
  locale/defaultMessages.json
  src/components/AssignAttributeDialog/AssignAttributeDialog.tsx
  src/components/AssignAttributeDialog/messages.ts
  src/components/ColumnPicker/ColumnPickerContent.tsx
  src/intl.ts
  src/permissionGroups/components/AssignMembersDialog/AssignMembersDialog.tsx
  src/permissionGroups/components/AssignMembersDialog/messages.ts
Labels: 3.1

#1687 Fix modal footer shadow issue
  locale/defaultMessages.json
  src/components/AssignAttributeDialog/AssignAttributeDialog.tsx
  src/components/AssignAttributeDialog/messages.ts
  src/components/ColumnPicker/ColumnPickerContent.tsx
  src/intl.ts
  src/permissionGroups/components/AssignMembersDialog/AssignMembersDialog.tsx
  src/permissionGroups/components/AssignMembersDialog/messages.ts
Labels: 3.0, reviewed

#1627 Add tests for variant selection
  cypress/elements/catalog/products/product-details.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/integration/configuration/attributes/attributeVariantSelection.js
  cypress/integration/preorders/createAndEditVariantsInPreorder.js
  cypress/support/api/requests/Product.js
  cypress/support/api/requests/ProductType.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: run e2e

#1662 Add tests for updating & deleting collections and categories
  cypress/elements/catalog/collection-selectors.js
  cypress/elements/shared/sharedElements.js
  cypress/fixtures/urlList.js
  cypress/integration/catalog/categories.js
  cypress/integration/catalog/collections.js
  cypress/support/api/requests/storeFront/Collections.js
  cypress/support/api/utils/storeFront/collectionsUtils.js
  cypress/support/customCommands/sharedElementsOperations/progressBar.js
  cypress/support/pages/catalog/categoriesPage.js
  cypress/support/pages/catalog/collectionsPage.js
Labels: run e2e

#1671 Fix failing cypress tests
  cypress/integration/configuration/channels/channels.js
  cypress/integration/configuration/shippingMethods/channelsInShipping.js
  cypress/integration/configuration/translations.js
  cypress/integration/discounts/sales/sales.js
  cypress/integration/discounts/vouchers.js
  cypress/integration/orders/orders.js
  cypress/integration/preorders/createAndEditVariantsInPreorder.js
  cypress/integration/preorders/stocksAndThreshold.js
  cypress/integration/products/images.js
  cypress/support/api/requests/Collections.js
  cypress/support/api/requests/Product.js
  cypress/support/api/utils/catalog/collectionsUtils.js
  cypress/support/customCommands/sharedElementsOperations/tables.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: run e2e

#1551 Disable save in product create & edit when product name is empty
  src/products/components/ProductCreatePage/form.tsx
  src/products/components/ProductUpdatePage/form.tsx
  src/products/components/ProductVariantPage/form.tsx
Labels: 3.0

#1701 Display error if no invoicing plugin is active
  CHANGELOG.md
  locale/defaultMessages.json
  schema.graphql
  src/fragments/types/MetadataFragment.ts
  src/orders/views/OrderDetails/index.tsx
  src/types/globalTypes.ts
  src/utils/metadata/types/UpdateMetadata.ts
  src/utils/metadata/types/UpdatePrivateMetadata.ts
Labels: 3.0

#1704 Fix assign attributes dialog loader
  src/components/AssignAttributeDialog/AssignAttributeDialog.tsx
Labels: 3.0

#1705 Fix assign attributes dialog loader
  src/components/AssignAttributeDialog/AssignAttributeDialog.tsx
Labels: 3.1

#1710 Disable save in product create & edit when product name is empty (#1551)
  src/products/components/ProductCreatePage/form.tsx
  src/products/components/ProductUpdatePage/form.tsx
Labels: 3.1, reviewed

#1709 Display error if no invoicing plugin is active
  locale/defaultMessages.json
  schema.graphql
  src/orders/views/OrderDetails/index.tsx
  src/types/globalTypes.ts
  src/webhooks/components/WebhookDetailsPage/WebhookDetailsPage.tsx
  src/webhooks/components/WebhookEvents/WebhookEvents.tsx
  src/webhooks/handlers.ts
  src/webhooks/types/WebhookDetails.ts
  src/webhooks/utils.ts
  src/webhooks/views/WebhooksCreate.tsx
  src/webhooks/views/WebhooksDetails.tsx
Labels: 3.1, reviewed

#1713 Update test for variants
  cypress/integration/products/productsVariants.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: run e2e

#1696 Use variant prices in add product modal
  src/components/DiscountedPrice/DiscountedPrice.tsx
  src/components/DiscountedPrice/styles.ts
  src/fragments/orders.ts
  src/fragments/types/OrderDetailsFragment.ts
  src/misc.ts
  src/orders/components/OrderPriceLabel/OrderPriceLabel.tsx
  src/orders/components/OrderPriceLabel/styles.ts
  src/orders/components/OrderProductAddDialog/OrderProductAddDialog.tsx
  src/orders/fixtures.ts
  src/orders/queries.ts
  src/orders/types/FulfillOrder.ts
  src/orders/types/OrderCancel.ts
  src/orders/types/OrderCapture.ts
  src/orders/types/OrderConfirm.ts
  src/orders/types/OrderDetails.ts
  src/orders/types/OrderDiscountAdd.ts
  src/orders/types/OrderDiscountDelete.ts
  src/orders/types/OrderDiscountUpdate.ts
  src/orders/types/OrderDraftCancel.ts
  src/orders/types/OrderDraftFinalize.ts
  src/orders/types/OrderDraftUpdate.ts
  src/orders/types/OrderFulfillmentCancel.ts
  src/orders/types/OrderFulfillmentRefundProducts.ts
  src/orders/types/OrderFulfillmentUpdateTracking.ts
  src/orders/types/OrderLineDelete.ts
  src/orders/types/OrderLineDiscountRemove.ts
  src/orders/types/OrderLineDiscountUpdate.ts
  src/orders/types/OrderLineUpdate.ts
  src/orders/types/OrderLinesAdd.ts
  src/orders/types/OrderMarkAsPaid.ts
  src/orders/types/OrderRefund.ts
  src/orders/types/OrderShippingMethodUpdate.ts
  src/orders/types/OrderUpdate.ts
  src/orders/types/OrderVoid.ts
  src/orders/types/SearchOrderVariant.ts
  src/orders/utils/data.ts
  src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
Labels: 3.0

#1698 Use variant prices in add product modal
  src/components/DiscountedPrice/DiscountedPrice.tsx
  src/components/DiscountedPrice/styles.ts
  src/fragments/orders.ts
  src/fragments/types/OrderDetailsFragment.ts
  src/misc.ts
  src/orders/components/OrderPriceLabel/OrderPriceLabel.tsx
  src/orders/components/OrderPriceLabel/styles.ts
  src/orders/components/OrderProductAddDialog/OrderProductAddDialog.tsx
  src/orders/fixtures.ts
  src/orders/queries.ts
  src/orders/types/FulfillOrder.ts
  src/orders/types/OrderCancel.ts
  src/orders/types/OrderCapture.ts
  src/orders/types/OrderConfirm.ts
  src/orders/types/OrderDetails.ts
  src/orders/types/OrderDiscountAdd.ts
  src/orders/types/OrderDiscountDelete.ts
  src/orders/types/OrderDiscountUpdate.ts
  src/orders/types/OrderDraftCancel.ts
  src/orders/types/OrderDraftFinalize.ts
  src/orders/types/OrderDraftUpdate.ts
  src/orders/types/OrderFulfillmentApprove.ts
  src/orders/types/OrderFulfillmentCancel.ts
  src/orders/types/OrderFulfillmentRefundProducts.ts
  src/orders/types/OrderFulfillmentUpdateTracking.ts
  src/orders/types/OrderLineDelete.ts
  src/orders/types/OrderLineDiscountRemove.ts
  src/orders/types/OrderLineDiscountUpdate.ts
  src/orders/types/OrderLineUpdate.ts
  src/orders/types/OrderLinesAdd.ts
  src/orders/types/OrderMarkAsPaid.ts
  src/orders/types/OrderRefund.ts
  src/orders/types/OrderShippingMethodUpdate.ts
  src/orders/types/OrderUpdate.ts
  src/orders/types/OrderVoid.ts
  src/orders/types/SearchOrderVariant.ts
  src/orders/utils/data.ts
  src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
Labels: 3.1, reviewed
