Repository saleor/saleor-dashboard, pull requests merged in 2022-10, with the labels that each got.

#2355 Fix e2e pages/pages.js, attributeVariantSelection.js
  cypress/support/api/requests/Attribute.js
Labels: tests

#2356 Fix revert to snapshot job
  .github/workflows/tests-nightly.yml
Labels: tests

#2349 Upgrade saleor version before test run
  .github/workflows/getUrlForReleaseTests.js
  .github/workflows/package-lock.json
  .github/workflows/package.json
  .github/workflows/tests-nightly.yml
Labels: tests

#2344 Update React to 17 and update related packages
  csstypes.d.ts
  package-lock.json
  package.json
  src/apps/apolloMocks.ts
  src/components/AppLayout/AppLayout.tsx
  src/components/ErrorPage/ErrorPage.tsx
  src/components/Metadata/Metadata.test.tsx
  src/components/Metadata/MetadataCard.tsx
  src/components/Navigator/useQuickSearch.ts
  src/components/TableCellAvatar/Avatar.tsx
  src/components/TableCellAvatar/TableCellAvatar.tsx
  src/components/TypeDeleteWarningDialog/DeleteWarningDialogConsentContent.tsx
  src/hooks/useElementScroll.ts
  src/index.tsx
  src/products/components/ProductUpdatePage/ProductUpdatePage.test.tsx
  src/storybook/Stories.test.ts
  src/storybook/stories/components/ErrorPage.tsx
Labels: run e2e

#2335 fix for manageStockReservation tests
  cypress/e2e/orders/manageStockReservation.js
  cypress/support/api/requests/ShopSettings.js
Labels: tests

#2362 Fix test nightly
  .github/workflows/tests-nightly.yml
Labels: tests

#2368 Fix tests nightly
  .github/workflows/getUrlForReleaseTests.js
  .github/workflows/tests-nightly.yml
Labels: tests

#2364 Fix tests for creating attributes
  cypress/e2e/configuration/attributes/createContentAttribute.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
Labels: tests

#2360 Wait for skeleton to disappear while searching for category to translate
  cypress/support/pages/translationsPage.js
Labels: tests

#2371 Extend description how to run automation tests in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tests

#2372 Fix tests for orders
  cypress/e2e/configuration/productTypes/attributesInProduductTypes.js
  cypress/e2e/discounts/vouchers/updateVouchers.js
  cypress/e2e/pages/pageTypes.js
  cypress/support/customCommands/sharedElementsOperations/assignElementsForm.js
  cypress/support/pages/draftOrderPage.js
Labels: tests

#2420 Remove unused imports and variables
  cypress/e2e/configuration/permissions.js
  cypress/e2e/configuration/productTypes/attributesInProduductTypes.js
  cypress/e2e/customerRegistration.js
  cypress/e2e/discounts/sales/updateSales.js
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/support/pages/catalog/collectionsPage.js
  cypress/support/pages/catalog/seoComponent.js
Labels: hacktoberfest, tests

#2411 Fix comments on release PRs
  .github/workflows/approveAndMergeReleasePR.js
  .github/workflows/tests-nightly.yml
Labels: tests

#2401 Fix tests for orders 3.6
  cypress/e2e/configuration/productTypes/attributesInProduductTypes.js
  cypress/e2e/discounts/vouchers/updateVouchers.js
  cypress/e2e/pages/pageTypes.js
  cypress/support/customCommands/sharedElementsOperations/assignElementsForm.js
  cypress/support/pages/draftOrderPage.js
Labels: tests

#2415 remove test for variant creator
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
Labels: hacktoberfest, run e2e, tests

#2418 Refactor product variants tests
  .github/PULL_REQUEST_TEMPLATE.md
  cypress/e2e/products/productsVariants.js
  cypress/support/pages/catalog/products/VariantsPage.js
  cypress/support/pages/catalog/products/productDetailsPage.js
Labels: hacktoberfest, tests

#2399 Fix tests for orders
  cypress/e2e/configuration/productTypes/attributesInProduductTypes.js
  cypress/e2e/discounts/vouchers/updateVouchers.js
  cypress/e2e/pages/pageTypes.js
  cypress/support/customCommands/sharedElementsOperations/assignElementsForm.js
  cypress/support/pages/draftOrderPage.js
Labels: tests

#2423 Fix for flaky TC:2902 test in productsVariants
  cypress/e2e/products/productsVariants.js
  cypress/support/pages/catalog/products/productDetailsPage.js
Labels: tests

#2424 2417 refactor variatns tests 3.7
  .github/PULL_REQUEST_TEMPLATE.md
  cypress/e2e/products/productsVariants.js
  cypress/support/pages/catalog/products/VariantsPage.js
  cypress/support/pages/catalog/products/productDetailsPage.js
Labels: tests

#2366 Fix tests for pages
  cypress/support/customCommands/sharedElementsOperations/selects.js
Labels: run e2e, tests

#2426 Fix tests for staff members
  cypress/support/api/utils/users.js
Labels: tests

#2427 Fix tests for pages
  cypress/support/customCommands/sharedElementsOperations/selects.js
Labels: tests

#2429 Fix tests for pages 3.6
  cypress/support/customCommands/sharedElementsOperations/selects.js
Labels: tests

#2431 Fix test for shipping method update
  cypress/elements/orders/draft-order-selectors.js
  cypress/elements/shared/sharedElements.js
  cypress/support/pages/draftOrderPage.js
  cypress/support/pages/shippingMethodPage.js
Labels: tests

#2440 Fix saving store settings
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/siteSettings/mutations.ts
  src/siteSettings/views/index.tsx
Labels: reviewed

#2436 Fix test for updating shipping method 3.7
  cypress/elements/orders/draft-order-selectors.js
  cypress/elements/shared/sharedElements.js
  cypress/support/pages/draftOrderPage.js
  cypress/support/pages/shippingMethodPage.js
Labels: tests

#2450 Remove set-output command in saleor-dashboard workflows
  .github/workflows/e2e.yml
  .github/workflows/test-env-cleanup.yml
  .github/workflows/test-env-deploy.yml
  .github/workflows/tests-nightly.yml
Labels: tests

#2398 Fix test for order refund
  cypress/e2e/homePage/homePageAnalitics.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/productsWithoutSku/productsWithoutSkuInOrder.js
  cypress/support/api/requests/Order.js
  cypress/support/api/requests/ShippingMethod.js
  cypress/support/api/utils/ordersUtils.js
Labels: tests

#2379 In old release versions run small package of most important tests
  .github/workflows/getEnvironmentVariables.js
  .github/workflows/tests-nightly.yml
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2351 Create workflow for building dashboard and executing tests
  .github/workflows/deploy-and-run-cypress.yml
Labels: tests

#2467 Remove adding sku to simple product
  cypress/e2e/products/productsWithoutSku/updatingProductsWithoutSku.js
Labels: tests

#2476 Disable test for weight recalculate
  cypress/e2e/configuration/shippingMethods/shippingWeights/weightRecalculate.js
Labels: tests

#2479 remove adding sku to simple product (#2467)
  cypress/e2e/products/productsWithoutSku/updatingProductsWithoutSku.js
Labels: tests

#2480 Disable test for weight recalculate 3.7
  cypress/e2e/configuration/shippingMethods/shippingWeights/weightRecalculate.js
Labels: tests

#2477 Activate plugins before tests
  cypress/e2e/configuration/plugins/plugins.js
  cypress/support/api/requests/Plugins.js
Labels: tests

#2462 Fix tests for metadata
  cypress/e2e/metadata.js
  cypress/support/api/requests/Metadata.js
Labels: tests

#2443 Disable demo staging deployment
  .github/workflows/deploy-demo-staging.yaml
Labels: bug

#2444 Disable demo staging deployment
  .github/workflows/deploy-demo-staging.yaml
Labels: bug

#2445 Disable demo staging deployment
  .github/workflows/deploy-demo-staging.yaml
Labels: bug

#2481 Disable test for weight recalculate 3.6
  cypress/e2e/configuration/shippingMethods/shippingWeights/weightRecalculate.js
Labels: tests

#2490 Activate plugins before tests - 3.7
  cypress/e2e/configuration/plugins/plugins.js
  cypress/support/api/requests/Plugins.js
Labels: tests

#2499 Fix failing tests in productType in 3.6
  cypress/support/customCommands/sharedElementsOperations/assignElementsForm.js
Labels: tests

#2497 Fix test should create simple product without sku SALEOR_2806
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/support/api/requests/Product.js
  cypress/support/customCommands/sharedElementsOperations/selects.js
Labels: tests
