Repository saleor/saleor-dashboard, pull requests merged in 2022-12, with the labels that each got.

#2729 Remove vidoes after cypress tests
  cypress.config.js
Labels: tests

#2750 Enabe strict bind call apply rule
  tsconfig.json
Labels: maintenance

#2646 [cypress] Add tests for delete several gift cards
  cypress/e2e/catalog/giftCards/updatingGiftCards.js
  cypress/elements/catalog/giftCard/giftCardList.js
  cypress/elements/catalog/giftCard/giftCardUpdate.js
  cypress/elements/catalog/products/products-list.js
  cypress/elements/shared/button-selectors.js
  src/components/DeleteIconButton/DeleteIconButton.tsx
  src/components/TableHead/TableHead.tsx
Labels: tests

#2785 Prevent infinite reloading service worker
  src/config.ts
  vite.config.js
Labels: bug

#2778 Fix run test on label after changing node to 18
  .github/workflows/e2e.yml
Labels: run e2e, tests

#2796 Fix test for email case insensitive
  cypress/e2e/configuration/customer.js
  cypress/e2e/staffMembers.js
  cypress/support/api/requests/Customer.js
  cypress/support/api/utils/users.js
  cypress/support/pages/draftOrderPage.js
Labels: tests

#2826 Remove double pkgs in pkg.json
  package-lock.json
  package.json
  src/storybook/config.js
Labels: run e2e

#2801 [cypress] add tests for gift cards bulk create and export
  .github/workflows/e2e.yml
  .github/workflows/test-env-deploy.yml
  cypress.config.js
  cypress/e2e/catalog/giftCards/exportGiftCards.js
  cypress/e2e/catalog/giftCards/updatingGiftCards.js
  cypress/elements/catalog/giftCard/giftCardShowMore.js
  cypress/support/api/requests/Plugins.js
  cypress/support/api/utils/users.js
  src/giftCards/GiftCardExportDialogContent/GiftCardExportDialogContent.tsx
Labels: tests

#2851 Fix strict null check in SiteSettings module
  src/siteSettings/components/SiteSettingsPage/SiteSettingsPage.tsx
  src/siteSettings/fixtures.ts
  src/siteSettings/index.tsx
  src/siteSettings/urls.ts
  src/siteSettings/views/index.tsx
Labels: maintenance

#2902 Cypress 2608 staff member tests
  cypress/e2e/catalog/giftCards/exportGiftCards.js
  cypress/e2e/staffMembers.js
  cypress/elements/shared/sharedElements.js
  cypress/elements/staffMembers/staffMemberDetails.js
  cypress/elements/staffMembers/staffMembersList.js
  cypress/support/api/requests/Plugins.js
  cypress/support/customCommands/sharedElementsOperations/confirmationMessages.js
  cypress/support/pages/userPage.js
  package-lock.json
  package.json
  src/staff/components/StaffList/StaffList.tsx
  src/staff/components/StaffPassword/StaffPassword.tsx
  src/staff/components/StaffPasswordResetDialog/StaffPasswordResetDialog.tsx
  src/staff/components/StaffProperties/StaffProperties.tsx
Labels: tests

#2910 Fix displaying ountry are as readable name
  src/components/AddressEdit/AddressEdit.tsx
  src/components/AddressEdit/useAddressValidation.test.ts
  src/components/AddressEdit/useAddressValidation.ts
  src/components/CompanyAddressInput/CompanyAddressForm.tsx
  src/siteSettings/components/SiteSettingsPage/SiteSettingsPage.tsx
Labels: bug

#2914 As an admin i want to manage attributes in product types -3.5
  cypress/support/customCommands/sharedElementsOperations/selects.js
  src/components/AssignAttributeDialog/AssignAttributeDialog.tsx
Labels: tests

#2911 Fix strict null check in Apps
  src/apps/components/AppActivateDialog/AppActivateDialog.stories.tsx
  src/apps/components/AppDeactivateDialog/AppDeactivateDialog.stories.tsx
  src/apps/components/AppDeleteDialog/AppDeleteDialog.stories.tsx
  src/apps/components/AppDetailsPage/AppDetailsPage.tsx
  src/apps/components/AppFrame/AppFrame.tsx
  src/apps/components/AppFrame/useAppActions.ts
  src/apps/components/AppFrame/useTokenRefresh.ts
  src/apps/components/AppInProgressDeleteDialog/AppInProgressDeleteDialog.stories.tsx
  src/apps/components/AppInstallPage/AppInstallPage.stories.tsx
  src/apps/components/AppInstallPage/AppInstallPage.tsx
  src/apps/components/AppPage/AppPage.stories.tsx
  src/apps/components/AppPage/AppPage.tsx
  src/apps/components/AppsInProgress/AppsInProgress.tsx
  src/apps/components/AppsListPage/AppListPage.stories.tsx
  src/apps/components/AppsListPage/AppsListPage.tsx
  src/apps/components/ExternalAppContext/context.ts
  src/apps/components/HorizontalSpacer/HorizontalSpacer.tsx
  src/apps/components/InstalledApps/InstalledApps.tsx
  src/apps/components/VerticalSpacer/VerticalSpacer.tsx
  src/apps/fixtures.ts
  src/apps/useExtensions.ts
  src/apps/views/App/App.tsx
  src/apps/views/AppDetails/AppDetails.tsx
  src/apps/views/AppInstall/AppInstall.tsx
  src/apps/views/AppSettings/AppSettings.tsx
  src/apps/views/AppsList/AppsList.tsx
  src/hooks/usePaginator.ts
  tsconfig.json
Labels: run e2e, maintenance
