Repository saleor/saleor-dashboard, pull requests merged in 2022-11, with the labels that each got.

#2486 Fix test for plugins 3.8
  cypress/e2e/configuration/plugins/plugins.js
  cypress/support/api/requests/Plugins.js
Labels: tests

#2457 tests: use env file for e2e tests
  README.md
  cypress/plugins/index.js
Labels: run e2e

#2494 Update Typescript
  package-lock.json
  package.json
  src/components/TableButtonWrapper/TableButtonWrapper.tsx
  src/navigation/components/MenuDetailsPage/tree.test.ts
  src/navigation/components/MenuDetailsPage/tree.ts
  src/navigation/components/MenuItems/MenuItems.tsx
  src/navigation/components/MenuItems/tree.test.ts
  src/navigation/components/MenuItems/tree.ts
  src/navigation/types.ts
Labels: dependencies, run e2e, maitenance

#2433 Add names of attributes translations
  introspection.json
  locale/defaultMessages.json
  schema.graphql
  src/fragments/translations.ts
  src/graphql/hooks.generated.ts
  src/graphql/typePolicies.generated.ts
  src/graphql/types.generated.ts
  src/translations/components/TranslationFields/TranslationFields.tsx
  src/translations/components/TranslationsPagesPage/TranslationsPagesPage.tsx
  src/translations/components/TranslationsProductVariantsPage/TranslationsProductVariantsPage.tsx
  src/translations/components/TranslationsProductsPage/TranslationsProductsPage.tsx
  src/translations/types.ts
  src/translations/utils.ts
  src/translations/views/TranslationsPages.tsx
  src/translations/views/TranslationsProductVariants.tsx
  src/translations/views/TranslationsProducts.tsx
Labels: bug

#2536 Add retries to cypress config
  cypress.config.js
Labels: tests

#2526 Fix tests for metadata 3.8
  cypress/e2e/metadata.js
  cypress/support/api/requests/Metadata.js
Labels: tests

#2527 Speed up releases
  .github/workflows/approveAndMergeReleasePR.js
Labels: tests

#2540 Wait for requests on add menu item page
  cypress/e2e/configuration/navigation.js
  cypress/support/pages/navigationPage.js
Labels: tests

#2543 Fix Create Products tests
  cypress/e2e/products/createProduct.js
Labels: tests

#2542 refactor c&c tests
  cypress/e2e/checkout/clickAndCollect.js
Labels: tests

#2537 Run cypress in repeat
  .github/workflows/cypress-repeat.yml
  cypress/support/cypress-grep/plugin.js
Labels: tests

#2548 Fix add comment to release PR with tests status
  .github/workflows/approveAndMergeReleasePR.js
Labels: tests

#2545 Fix adyen tests
  .github/PULL_REQUEST_TEMPLATE.md
  cypress/e2e/configuration/plugins/adyen.js
  cypress/support/api/requests/Plugins.js
Labels: run e2e, tests

#2555 Fix for addUserToPermissionGroup test and refactor of permissions tests
  cypress/e2e/configuration/permissions.js
  cypress/elements/permissionGroup/permissionGroupDetails.js
Labels: tests

#2564 Wait for requests on add menu item page 3.6
  cypress/e2e/configuration/navigation.js
  cypress/support/pages/navigationPage.js
Labels: tests

#2560 Fix tests for customer registration and reset password
  cypress/e2e/customerRegistration.js
  cypress/e2e/staffMembers.js
  cypress/plugins/index.js
  cypress/support/api/utils/users.js
Labels: run e2e, tests

#2577 Fix issue url in release PR
  .github/workflows/approveAndMergeReleasePR.js
Labels: tests

#2565 Wait for requests on add menu item page 3.7
  cypress/e2e/configuration/navigation.js
  cypress/support/pages/navigationPage.js
Labels: tests

#2563 wait for requests on add menu item page 3.5
  cypress/e2e/configuration/navigation.js
  cypress/support/pages/navigationPage.js
Labels: tests

#2528 Fix product channels update error
  src/products/views/ProductUpdate/handlers/utils.test.ts
  src/products/views/ProductUpdate/handlers/utils.ts
Labels: bug, datagrid, Feature: DataGrid

#2596 Add squash method when merging release pull requests
  .github/workflows/approveAndMergeReleasePR.js
Labels: tests

#2594 Fix nightly tests after changing node to 18
  .github/workflows/tests-nightly.yml
Labels: tests

#2562 Removing returnUrl to fix stock test
  cypress/support/api/requests/Checkout.js
Labels: tests

#2547 Create workflow to run tests in loop for detecting flaky tests
  .github/workflows/cypress-repeat.yml
Labels: tests

#2663 On release tests run only critical paths
  .github/workflows/approveAndMergeReleasePR.js
  .github/workflows/tests-nightly.yml
Labels: tests

#2693 Add @oldRelease tag to selected tests -3.1
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2694 add @oldRelease tag to selected tests -3.2
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2696 add @oldRelease tag to selected tests -3.4
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2697 Add @oldRelease tag to selected tests -3.5
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2699 Remove tests for preorders
  cypress/e2e/preorders/createAndEditVariantsInPreorder.js
  cypress/e2e/preorders/stocksAndThreshold.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/support/api/requests/Product.js
  cypress/support/api/utils/products/productsUtils.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: tests

#2695 add @oldRelease tag to selected tests -3.3
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2698 Add old release tag to selected tests - 3.6
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2701 add oldRelease tag to selected tests
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/checkout/warehouses.js
  cypress/e2e/configuration/attributes/createProductAttributes.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/productTypes/createProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/homePage/homePage.js
  cypress/e2e/login.js
  cypress/e2e/navigation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/productsVariants.js
Labels: tests

#2708 remove tests for preorders in 3.7 (#2699)
  cypress/e2e/preorders/createAndEditVariantsInPreorder.js
  cypress/e2e/preorders/stocksAndThreshold.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/support/api/requests/Product.js
  cypress/support/api/utils/products/productsUtils.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: tests

#2703 Remove tests for preorders in 3.8 (#2699)
  cypress/e2e/preorders/createAndEditVariantsInPreorder.js
  cypress/e2e/preorders/stocksAndThreshold.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/support/api/requests/Product.js
  cypress/support/api/utils/products/productsUtils.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: tests

#2728 Fix test for navigation
  cypress/fixtures/permissions.js
  cypress/fixtures/permissionsUsers.js
Labels: tests

#2711 Fix issue with expired token when running tests in interactive mode
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/support/api/requests/utils/index.js
  cypress/support/customCommands/user/index.js
  cypress/support/e2e.js
Labels: tests

#2709 Enable no implicit this
  src/orders/views/OrderReturn/utils.tsx
  tsconfig.json
Labels: maitenance

#2710 Enable always strict rule
  tsconfig.json
Labels: maitenance

#2745 Fix tags in cypress nightly tests
  .github/workflows/tests-nightly.yml
Labels: tests
