Repository saleor/saleor-dashboard, pull requests merged in 2022-01, with the labels that each got.

#1711 Fix EditorJS read-mode toggle race condition
  package-lock.json
  package.json
  src/components/RichTextEditor/RichTextEditor.tsx
  src/misc.ts
Labels: 3.1

#1712 Fix EditorJS read-mode toggle race condition
  package-lock.json
  package.json
  src/components/RichTextEditor/RichTextEditor.tsx
  src/misc.ts
Labels: 3.0

#1740 Rename ExpansionPanel components to Accordion (#1727)
  src/components/Timeline/TimelineEvent.tsx
Labels: 3.1, reviewed

#1721 Logout redirects user to home page
  src/auth/AuthProvider.test.tsx
  src/auth/hooks/useAuthProvider.ts
Labels: 3.1, reviewed

#1722 Show "not found" page if app doesn't exist
  src/apps/views/AppDetails/AppDetails.tsx
  src/apps/views/AppDetailsSettings/AppDetailsSettings.tsx
Labels: 3.0

#1542 Adjust changed permission requirements
  src/hooks/makeTopLevelSearch/makeTopLevelSearch.ts
  src/orders/components/OrderCustomer/OrderCustomer.tsx
Labels: reviewed

#1720 Record test in cypress dashboard
  .github/workflows/e2e.yml
  .gitignore
  cypress.json
  package-lock.json
  package.json
Labels: run e2e

#1730 Fix switch account login and credentials API wrong login loop issues
  src/auth/hooks/useAuthProvider.ts
  src/utils/credentialsManagement.ts
Labels: 3.0

#1737 Fix overflow issue in export dialog
  src/products/components/ProductExportDialog/ProductExportDialogInfo.tsx
Labels: 3.1

#1761 Fix link hrefs
  src/misc.ts
  src/orders/components/OrderCustomer/OrderCustomer.tsx
  src/products/components/ProductOrganization/ProductOrganization.tsx
Labels: reviewed

#1752 Scroll to top on main navigation routes changes
  src/components/AppLayout/AppLayout.tsx
Labels: 3.1

#1753 Scroll to top on main navigation routes changes
  src/components/AppLayout/AppLayout.tsx
Labels: 3.0

#1743 Redirect user back to the first landing page after external login
  src/auth/views/Login.tsx
Labels: 3.0

#1763 Removing collection fix
  src/misc.ts
  src/utils/handlers/multiAutocompleteSelectChangeHandler.ts
Labels: 3.0

#1764 Removing collection fix
  src/misc.ts
  src/utils/handlers/multiAutocompleteSelectChangeHandler.ts
Labels: 3.1

#1790 Redirect user to created variant after variant create
  locale/defaultMessages.json
  src/products/views/ProductVariantCreate.tsx
  src/products/views/messages.ts
Labels: 3.1, reviewed

#1795 Fix navigation on crash error
  src/components/AppLayout/AppLayout.tsx
Labels: 3.1

#1793 Fix error on language change
  src/auth/hooks/useAuthProvider.ts
Labels: 3.1
