Repository saleor/saleor-dashboard, pull requests merged in 2022-04, with the labels that each got.

#1936 Fix channels in shipping
  .github/workflows/test-env-deploy.yml
  cypress/integration/configuration/shippingMethods/channelsInShipping.js
  cypress/support/api/utils/shippingUtils.js
Labels: tests

#1979 removing hardcoded keys and adding CYPRESS_RECORD_KEY variable
  .github/workflows/e2e.yml
  package.json
Labels: run e2e, tests

#1953 copping solution form 3.0 branch
  cypress/integration/configuration/attributes/createContentAttribute.js
  cypress/integration/configuration/attributes/createProductAttributes.js
  cypress/integration/configuration/attributes/deleteAndUpdateContentAttribute.js
  package-lock.json
Labels: tests

#1991 Fix Critical
  .github/PULL_REQUEST_TEMPLATE.md
  cypress/integration/checkout/purchaseWithProductTypes.js
  cypress/integration/checkout/stocksInCheckout.js
  cypress/integration/products/productsVariants.js
  cypress/support/api/utils/products/productsUtils.js
  cypress/support/pages/catalog/products/VariantsPage.js
  package.json
Labels: tests

#2007 Create workflow for nightly tests
  .github/workflows/tests-nightly.yml
  package.json
Labels: tests

#2016 Fix tests for products attributes
  cypress/integration/configuration/productTypes/attributesInProduductTypes.js
Labels: tests

#2017 Switch snapshot to restore in nightly tests
  .github/workflows/tests-nightly.yml
Labels: tests

#1952 Adding missing test to collections tests
  cypress/elements/catalog/collection-selectors.js
  cypress/integration/catalog/collections.js
  cypress/support/api/requests/Collections.js
  cypress/support/pages/catalog/collectionsPage.js
  src/collections/components/CollectionProducts/CollectionProducts.tsx
  src/collections/views/CollectionList/CollectionList.tsx
Labels: tests

#1975 Fix tests for categories
  cypress/integration/catalog/categories.js
  cypress/support/api/requests/Checkout.js
Labels: tests

#2012 Fix tests for vouchers
  cypress/support/customCommands/softAssertions/index.js
  cypress/support/pages/discounts/vouchersPage.js
Labels: tests

#2023 Add input for cypress workflow
  .github/workflows/tests-nightly.yml
Labels: tests

#1896 Fulfillment creation refactor
  locale/defaultMessages.json
  src/fragments/orders.ts
  src/fragments/products.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/hooks/makeQuery.ts
  src/misc.ts
  src/orders/components/OrderCardTitle/OrderCardTitle.tsx
  src/orders/components/OrderCardTitle/index.ts
  src/orders/components/OrderChangeWarehouseDialog/OrderChangeWarehouseDialog.stories.tsx
  src/orders/components/OrderChangeWarehouseDialog/OrderChangeWarehouseDialog.tsx
  src/orders/components/OrderChangeWarehouseDialog/index.ts
  src/orders/components/OrderChangeWarehouseDialog/messages.ts
  src/orders/components/OrderChangeWarehouseDialog/styles.ts
  src/orders/components/OrderDetailsPage/OrderDetailsPage.tsx
  src/orders/components/OrderFulfillLine/OrderFulfillLine.tsx
  src/orders/components/OrderFulfillLine/index.ts
  src/orders/components/OrderFulfillLine/messages.ts
  src/orders/components/OrderFulfillLine/styles.ts
  src/orders/components/OrderFulfillPage/OrderFulfillPage.stories.tsx
  src/orders/components/OrderFulfillPage/OrderFulfillPage.tsx
  src/orders/components/OrderFulfillPage/messages.ts
  src/orders/components/OrderFulfillPage/styles.ts
  src/orders/components/OrderFulfillStockExceededDialog/OrderFulfillStockExceededDialog.tsx
  src/orders/components/OrderFulfillStockExceededDialog/index.tsx
  src/orders/components/OrderFulfillStockExceededDialog/messages.ts
  src/orders/components/OrderFulfillStockExceededDialog/styles.ts
  src/orders/components/OrderFulfillStockExceededDialogLine/OrderFulfillStockExceededDialogLine.tsx
  src/orders/components/OrderFulfillStockExceededDialogLine/index.tsx
  src/orders/components/OrderFulfilledProductsCard/OrderFulfilledProductsCard.tsx
  src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/CardTitle.tsx
  src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ReturnItemsCard.tsx
  src/orders/components/OrderUnfulfilledProductsCard/OrderUnfulfilledProductsCard.tsx
  src/orders/fixtures.ts
  src/orders/index.tsx
  src/orders/mutations.ts
  src/orders/queries.ts
  src/orders/urls.ts
  src/orders/utils/data.test.ts
  src/orders/utils/data.ts
  src/orders/views/OrderDetails/OrderNormalDetails/index.tsx
  src/orders/views/OrderDetails/OrderNormalDetails/useDefaultWarehouse.ts
  src/orders/views/OrderFulfill/OrderFulfill.tsx
  src/searches/useWarehouseSearch.ts
  src/storybook/stories/orders/OrderDetailsPage.tsx
Labels: Feature branch

#2029 Exclude failing tests from executing
  cypress/integration/catalog/collections.js
  cypress/integration/catalog/giftCards/activateGiftCards.js
  cypress/integration/products/productsList/filteringProducts.js
Labels: tests
