Repository saleor/saleor-dashboard, pull requests merged in 2022-02, with the labels that each got.

#1811 Add hover tooltip on sorting disabled columns
  locale/defaultMessages.json
  src/collections/components/CollectionList/CollectionList.tsx
  src/collections/components/CollectionListPage/CollectionListPage.tsx
  src/components/TableCellHeader/TableCellHeader.tsx
  src/components/TooltipTableCellHeader/TooltipTableCellHeader.tsx
  src/components/TooltipTableCellHeader/index.ts
  src/components/TooltipTableCellHeader/messages.ts
  src/discounts/components/SaleList/SaleList.tsx
  src/discounts/components/SaleListPage/SaleListPage.tsx
  src/discounts/components/VoucherList/VoucherList.tsx
  src/discounts/components/VoucherListPage/VoucherListPage.tsx
  src/giftCards/GiftCardsList/GiftCardListSearchAndFilters/filters.ts
  src/giftCards/GiftCardsList/GiftCardsListTable/GiftCardsListTableHeader/GiftCardsListTableHeader.tsx
  src/products/components/ProductList/ProductList.tsx
  src/products/components/ProductListPage/ProductListPage.tsx
  src/types.ts
Labels: 3.1

#1829 Fix select all channels checkbox in product export
  src/products/components/ProductExportDialog/ProductExportDialogInfo.tsx
Labels: 3.0

#1828 Fix select all channels checkbox in product export
  src/products/components/ProductExportDialog/ProductExportDialogInfo.tsx
Labels: 3.1

#1830 Bump up debounce rate
  src/components/SearchBar/SearchInput.tsx
Labels: 3.0

#1831 Bump up debounce rate
  src/components/SearchBar/SearchInput.tsx
Labels: 3.1

#1840 Run e2e at night
  .github/workflows/run-e2e-at-night.yml
  cypress/plugins/index.js
  package-lock.json
  package.json
Labels: tests

#1808 Add tests for creating vouchers
  cypress/elements/discounts/vouchers.js
  cypress/integration/checkout/purchaseWithProductTypes.js
  cypress/integration/configuration/plugins/adyen.js
  cypress/integration/discounts/sales/salesForProducts.js
  cypress/integration/discounts/sales/salesForVariants.js
  cypress/integration/discounts/salesForProducts.js
  cypress/integration/discounts/salesForVariants.js
  cypress/integration/discounts/vouchers.js
  cypress/integration/discounts/vouchers/createVouchers.js
  cypress/integration/discounts/vouchers/vouchers.js
  cypress/support/api/requests/Checkout.js
  cypress/support/api/utils/ordersUtils.js
  cypress/support/pages/discounts/vouchersPage.js
  src/components/ControlledCheckbox.tsx
  src/discounts/components/VoucherLimits/VoucherLimits.tsx
Labels: tests

#1834 fixing CLA issie
  cypress/elements/translations/element-translation.js
  cypress/integration/translations.js
  cypress/support/pages/translationsPage.js
  package-lock.json
  src/translations/components/TranslationFields/TranslationFieldsLong.tsx
  src/translations/components/TranslationFields/TranslationFieldsRich.tsx
  src/translations/components/TranslationFields/TranslationFieldsShort.tsx
Labels: tests

#1836 Prevent needless metadata updates
  src/fragments/types/MetadataFragment.ts
  src/utils/handlers/metadataUpdateHandler.ts
  src/utils/handlers/metadataUpdateHelpers.ts
  src/utils/metadata/types/UpdateMetadata.ts
  src/utils/metadata/types/UpdatePrivateMetadata.ts
  src/utils/metadata/updateMetadata.ts
Labels: 3.0

#1860 Prevent needless metadata updates
  src/utils/handlers/metadataUpdateHandler.ts
  src/utils/handlers/metadataUpdateHelpers.ts
  src/utils/metadata/types/UpdateMetadata.ts
  src/utils/metadata/types/UpdatePrivateMetadata.ts
  src/utils/metadata/updateMetadata.ts
Labels: 3.1, reviewed

#1823 Add test for automatically confirm all new orders in orders settings
  cypress/elements/catalog/categories/categories-list.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/elements/orders/orders-settings-selectors.js
  cypress/elements/shared/sharedElements.js
  cypress/fixtures/urlList.js
  cypress/integration/checkout/purchaseWithProductTypes.js
  cypress/integration/checkout/stocksInCheckout.js
  cypress/integration/configuration/productTypes.js
  cypress/integration/homePage/homePageAnalitics.js
  cypress/integration/orders/channelsInDraftOrders.js
  cypress/integration/orders/draftOrders.js
  cypress/integration/orders/fulfillOrdersWithoutStock.js
  cypress/integration/orders/orders.js
  cypress/integration/orders/ordersSettings.js
  cypress/integration/translations.js
  cypress/support/pages/catalog/products/VariantsPage.js
  cypress/support/pages/orderPage.js
  cypress/support/pages/orders/orderPage.js
  cypress/support/pages/orders/ordersSettingsPage.js
  package-lock.json
  src/components/DeleteButton/DeleteButton.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
  src/products/components/ProductList/ProductList.tsx
Labels: run e2e, tests

#1832 Add tests for manage stock reservation
  cypress/elements/siteSettings/site-settings-details.js
  cypress/integration/orders/manageStockReservation.js
  cypress/support/api/requests/Checkout.js
  cypress/support/api/requests/ShopSettings.js
  cypress/support/pages/siteSettings.js
Labels: tests

#1854 Fix external refresh token error
  package-lock.json
  package.json
Labels: 3.0

#1852 Fix external refresh token error
  package-lock.json
  package.json
Labels: 3.1

#1835 Fix failing test for 3.0
  cypress/elements/shared/button-selectors.js
  cypress/integration/checkout/productWithoutShipping.js
  cypress/integration/checkout/purchaseWithProductTypes.js
  cypress/integration/configuration/productTypes.js
  cypress/integration/orders/orders.js
  cypress/support/api/requests/Checkout.js
  cypress/support/api/utils/ordersUtils.js
  cypress/support/api/utils/storeFront/checkoutUtils.js
  src/components/DeleteButton/DeleteButton.tsx
  src/components/TypeDeleteWarningDialog/TypeDeleteWarningDialogContent.tsx
  src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
  src/products/components/ProductList/ProductList.tsx
Labels: tests

#1838 Updated names for attributes tests on 3.0 according to guide new
  cypress/integration/configuration/attributes/attributes.js
  cypress/integration/configuration/attributes/createContentAttribute.js
  cypress/integration/configuration/attributes/deleteAndUpdateContentAttribute.js
Labels: tests

#1868 fixed issues with CLA, and added tests for update translation
  cypress/elements/translations/element-translation.js
  cypress/integration/configuration/translations.js
  cypress/integration/translations.js
  cypress/support/api/requests/Category.js
  cypress/support/pages/translationPage.js
  cypress/support/pages/translationsPage.js
  src/translations/components/TranslationFields/TranslationFieldsLong.tsx
  src/translations/components/TranslationFields/TranslationFieldsRich.tsx
  src/translations/components/TranslationFields/TranslationFieldsShort.tsx
Labels: tests
