Repository saleor/saleor-dashboard, pull requests merged in 2023-08, with the labels that each got.

#4036 Introduce datagrid on voucher list view
  .changeset/soft-buses-roll.md
  locale/defaultMessages.json
  src/config.ts
  src/discounts/components/SaleListDatagrid/messages.ts
  src/discounts/components/VoucherListDatagrid/VoucherListDatagrid.tsx
  src/discounts/components/VoucherListDatagrid/datagrid.ts
  src/discounts/components/VoucherListDatagrid/index.ts
  src/discounts/components/VoucherListDatagrid/messages.ts
  src/discounts/components/VoucherListPage/VoucherListPage.stories.tsx
  src/discounts/components/VoucherListPage/VoucherListPage.tsx
  src/discounts/views/VoucherList/VoucherList.tsx
  src/discounts/views/VoucherList/filters.ts
  src/hooks/useFilterPresets/useFilterPresets.ts
Labels: run e2e

#3515 Assign channel to permission group
  .changeset/twenty-ways-reflect.md
  .storybook/helpers/MockedUserProvider.tsx
  introspection.json
  locale/defaultMessages.json
  src/auth/hooks/useAuthProvider.ts
  src/auth/hooks/useUserAccessibleChannels.ts
  src/auth/index.tsx
  src/auth/types.ts
  src/components/AccountPermissions/AccountPermissions.tsx
  src/components/AccountPermissions/components/Header/Header.tsx
  src/components/AccountPermissions/components/Header/index.ts
  src/components/AccountPermissions/components/PermissionExeeded/PermissionExeeded.tsx
  src/components/AccountPermissions/components/PermissionExeeded/index.ts
  src/components/AccountPermissions/components/PermissionList/PermissionList.tsx
  src/components/AccountPermissions/components/PermissionList/index.ts
  src/components/AccountPermissions/messages.ts
  src/components/AccountPermissions/utils.ts
  src/components/AppLayout/AppChannelContext.tsx
  src/components/AppLayout/TopNav/Root.tsx
  src/components/ChannelPermission/ChannelPermission.test.tsx
  src/components/ChannelPermission/ChannelPermission.tsx
  src/components/ChannelPermission/fixtures.ts
  src/components/ChannelPermission/index.ts
  src/components/ChannelPermission/messages.ts
  src/components/Shop/queries.ts
  src/configuration/ConfigurationPage.stories.tsx
  src/fixtures.ts
  src/fragments/auth.ts
  src/fragments/permissionGroups.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/home/queries.ts
  src/home/views/index.tsx
  src/orders/components/OrderDraftListHeader/OrderDraftListHeader.tsx
  src/orders/components/OrderListPage/OrderListPage.tsx
  src/orders/views/OrderDraftList/OrderDraftList.tsx
  src/orders/views/OrderList/OrderList.tsx
  src/permissionGroups/components/PermissionGroupCreatePage/PermissionGroupCreatePage.stories.tsx
  src/permissionGroups/components/PermissionGroupCreatePage/PermissionGroupCreatePage.tsx
  src/permissionGroups/components/PermissionGroupCreatePage/index.ts
  src/permissionGroups/components/PermissionGroupDetailsPage/PermissionGroupDetailsPage.stories.tsx
  src/permissionGroups/components/PermissionGroupDetailsPage/PermissionGroupDetailsPage.tsx
  src/permissionGroups/components/PermissionGroupDetailsPage/index.ts
  src/permissionGroups/fixtures.ts
  src/permissionGroups/index.tsx
  src/permissionGroups/sort.ts
  src/permissionGroups/utils.test.ts
  src/permissionGroups/utils.ts
  src/permissionGroups/views/PermissionGroupCreate/PermissionGroupCreate.tsx
  src/permissionGroups/views/PermissionGroupCreate/index.ts
  src/permissionGroups/views/PermissionGroupDetails/PermissionGroupDetails.tsx
  src/permissionGroups/views/PermissionGroupDetails/index.ts
  src/permissionGroups/views/PermissionGroupList/PermissionGroupList.tsx
  src/permissionGroups/views/PermissionGroupList/sort.ts
  src/types.ts
  src/utils/errors/permissionGroups.ts
Labels: run e2e

#4070 Display gift card on order
  locale/defaultMessages.json
  src/orders/components/OrderPayment/OrderPayment.tsx
  src/orders/components/OrderPayment/messages.ts
  src/orders/components/OrderPayment/utils.ts
  src/orders/components/OrderSummaryCard/OrderSummaryCard.tsx
  src/orders/components/OrderSummaryCard/messages.ts
Labels: view: gift cards

#4034 Test maintenance - draft orders, pagination, create page
  cypress/e2e/orders/draftOrders.js
  cypress/e2e/pages/pages.js
  cypress/e2e/products/productsList/pagination.js
  cypress/support/api/requests/Order.js
  cypress/support/api/requests/index.js
  cypress/support/customCommands/sharedElementsOperations/selects.js
Labels: automation tests

#4059 Use common method to delete filter presets
  .changeset/kind-points-warn.md
  src/categories/views/CategoryList/CategoryList.tsx
  src/collections/views/CollectionList/CollectionList.tsx
  src/customers/views/CustomerList/CustomerList.tsx
  src/discounts/views/SaleList/SaleList.tsx
  src/giftCards/GiftCardsList/GiftCardListSearchAndFilters/GiftCardListSearchAndFilters.tsx
  src/hooks/useFilterPresets/useFilterPresets.test.ts
  src/hooks/useFilterPresets/useFilterPresets.ts
  src/orders/views/OrderDraftList/OrderDraftList.tsx
  src/orders/views/OrderList/OrderList.tsx
  src/pages/views/PageList/PageList.tsx
  src/products/views/ProductList/ProductList.tsx
Labels: run e2e

#4102 Introduce datagrid to permission group list
  .changeset/sharp-wombats-teach.md
  cypress/e2e/configuration/permissions.js
  locale/defaultMessages.json
  src/config.ts
  src/permissionGroups/components/PermissionGroupDetailsPage/PermissionGroupDetailsPage.stories.tsx
  src/permissionGroups/components/PermissionGroupDetailsPage/PermissionGroupDetailsPage.tsx
  src/permissionGroups/components/PermissionGroupList/PermissionGroupList.tsx
  src/permissionGroups/components/PermissionGroupList/index.ts
  src/permissionGroups/components/PermissionGroupListDatagrid/PermissionGroupListDatagrid.tsx
  src/permissionGroups/components/PermissionGroupListDatagrid/datagrid.ts
  src/permissionGroups/components/PermissionGroupListDatagrid/index.ts
  src/permissionGroups/components/PermissionGroupListDatagrid/messages.ts
  src/permissionGroups/components/PermissionGroupListPage/PermissionGroupListPage.stories.tsx
  src/permissionGroups/components/PermissionGroupListPage/PermissionGroupListPage.tsx
  src/permissionGroups/views/PermissionGroupDetails/PermissionGroupDetails.tsx
  src/permissionGroups/views/PermissionGroupList/PermissionGroupList.tsx
  src/permissionGroups/views/PermissionGroupList/sort.ts
Labels: run e2e

#4136 Fix showing only first 50 warehouses at variant page
  .changeset/nervous-pigs-clap.md
  src/hooks/makeFetchAll.ts
  src/products/components/ProductStocks/ProductStocks.tsx
  src/products/components/ProductVariantPage/ProductVariantPage.tsx
  src/products/components/ProductVariantPage/ProductVarinatPage.stories.tsx
  src/products/views/ProductVariant/ProductVariant.tsx
  src/products/views/ProductVariant/utils.ts
Labels: run e2e
