Repository saleor/saleor-dashboard, pull requests merged in 2023-03, with the labels that each got.

#3167 Migrate app details view (settings view) to new-apps
  locale/defaultMessages.json
  src/apps/components/AppActivateDialog/AppActivateDialog.tsx
  src/apps/components/AppActivateDialog/index.ts
  src/apps/components/AppDeactivateDialog/AppDeactivateDialog.tsx
  src/apps/components/AppDeactivateDialog/index.ts
  src/apps/components/AppDeactivateDialog/messages.ts
  src/apps/components/AppDeleteDialog/AppDeleteDialog.tsx
  src/apps/components/AppDeleteDialog/index.ts
  src/apps/components/AppDetailsPage/AppDetailsPage.tsx
  src/apps/index.tsx
  src/custom-apps/components/CustomAppListPage/CustomAppListPage.tsx
  src/custom-apps/views/CustomAppDetails/CustomAppDetails.tsx
  src/custom-apps/views/CustomAppList.tsx
  src/intl.ts
  src/new-apps/components/AppDetailsPage/AboutCard.tsx
  src/new-apps/components/AppDetailsPage/AppDetailsPage.stories.tsx
  src/new-apps/components/AppDetailsPage/AppDetailsPage.test.tsx
  src/new-apps/components/AppDetailsPage/AppDetailsPage.tsx
  src/new-apps/components/AppDetailsPage/DataPrivacyCard.tsx
  src/new-apps/components/AppDetailsPage/Header.test.tsx
  src/new-apps/components/AppDetailsPage/Header.tsx
  src/new-apps/components/AppDetailsPage/HeaderOptions.tsx
  src/new-apps/components/AppDetailsPage/PermissionsCard.tsx
  src/new-apps/components/AppDetailsPage/index.ts
  src/new-apps/components/AppDetailsPage/messages.ts
  src/new-apps/components/AppDetailsPage/styles.ts
  src/new-apps/components/DeactivatedText/DeactivatedText.tsx
  src/new-apps/components/DeactivatedText/index.ts
  src/new-apps/components/DeactivatedText/styles.ts
  src/new-apps/index.tsx
  src/new-apps/messages.ts
  src/new-apps/views/AppDetails/AppDetails.tsx
  src/new-apps/views/AppDetails/index.ts
  src/new-apps/views/AppDetails/messages.ts
Labels: Feature: Apps

#3240 Migrate app install view to new-apps
  src/apps/index.tsx
  src/apps/messages.ts
  src/apps/views/AppsList/AppsList.tsx
  src/custom-apps/views/CustomAppDetails/CustomAppDetails.tsx
  src/custom-apps/views/CustomAppList.tsx
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/new-apps/components/AppInstallErrorPage/AppInstallErrorPage.tsx
  src/new-apps/components/AppInstallErrorPage/index.ts
  src/new-apps/components/AppInstallErrorPage/messages.ts
  src/new-apps/components/AppInstallErrorPage/styles.ts
  src/new-apps/components/AppInstallPage/AppInstallPage.stories.tsx
  src/new-apps/components/AppInstallPage/AppInstallPage.tsx
  src/new-apps/components/AppInstallPage/index.ts
  src/new-apps/components/AppInstallPage/messages.ts
  src/new-apps/components/AppInstallPage/styles.ts
  src/new-apps/components/ExternalAppContext/ExternalAppContext.tsx
  src/new-apps/components/ExternalAppContext/context.ts
  src/new-apps/hooks/useActiveAppsInstallations.ts
  src/new-apps/index.tsx
  src/new-apps/mutations.ts
  src/new-apps/queries.ts
  src/new-apps/tsconfig.json
  src/new-apps/urls.ts
  src/new-apps/views/AppDetails/AppDetails.tsx
  src/new-apps/views/AppInstall/AppInstall.tsx
  src/new-apps/views/AppInstall/index.ts
  src/new-apps/views/AppInstall/messages.ts
  src/new-apps/views/AppView/AppView.tsx
  testUtils/mocks/apps.ts
Labels: run e2e, Feature: Apps

#3312 fixed test SALEOR_0808
  cypress/elements/shipping/shipping-zone-details.js
  cypress/support/pages/shippingMethodPage.js
  src/shipping/components/ShippingZoneInfo/ShippingZoneInfo.tsx
Labels: run e2e

#3313 Fix overflowing integrations in app view
  package-lock.json
  src/apps/components/AppListCard/AppListCard.tsx
  src/apps/components/AppListCard/AppListCardIntegrations.tsx
  src/apps/components/AppListCard/AppListCardLinks.tsx
Labels: bug

#3347 Fix custom app crush when no permissions
  src/components/AccountPermissions/AccountPermissions.tsx
Labels: run e2e

#3371 Fix adding empty order line in order drafts & unconfirmed orders
  src/orders/components/OrderProductAddDialog/OrderProductAddDialog.tsx
  src/orders/utils/data.ts
  src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
  src/orders/views/OrderDetails/OrderNormalDetails/index.tsx
  src/orders/views/OrderDetails/OrderUnconfirmedDetails/index.tsx
Labels: run e2e

#3333 Add DevMode panel (trigger: `CMD+'`)
  CHANGELOG.md
  locale/defaultMessages.json
  src/components/AppLayout/AppLayout.tsx
  src/components/DevModePanel/DevModePanel.tsx
  src/components/DevModePanel/DevModeProvider.tsx
  src/components/DevModePanel/hooks.ts
  src/components/DevModePanel/index.ts
  src/components/DevModePanel/messages.ts
  src/components/DevModePanel/useDevModeKeyTrigger.ts
  src/components/GraphiQL/GraphiQL.tsx
  src/components/GraphiQL/styles.ts
  src/components/GraphiQLPlain/GraphiQL.tsx
  src/components/GraphiQLPlain/index.ts
  src/index.tsx
  src/orders/components/OrderDetailsPage/OrderDetailsPage.tsx
  src/products/components/ProductUpdatePage/ProductUpdatePage.tsx
Labels: fast-lane, Beta

#3386 Migrate to `es2020` for TS
  CHANGELOG.md
  tsconfig.json
Labels: run e2e

#3387 Use TypeScript 5.x significantly smaller & faster
  package-lock.json
  package.json
  src/custom-apps/components/WebhookSubscriptionQuery/WebhookSubscriptionQuery.tsx
  src/orders/components/OrderRefundReturnAmount/OrderRefundReturnAmount.tsx
Labels: run e2e

#3411 fixing failing tests
  cypress/e2e/configuration/channels/channels.js
  cypress/e2e/navigation.js
  cypress/e2e/products/productsList/filteringProducts.js
  cypress/e2e/products/productsList/pagination.js
  cypress/e2e/products/productsList/sortingProducts.js
  cypress/elements/catalog/products/products-list.js
  cypress/elements/index.js
  cypress/elements/navigation/index.js
  cypress/elements/navigation/pagination.js
  cypress/elements/shared/sharedElements.js
  cypress/support/customCommands/basicOperations/index.js
  cypress/support/customCommands/sharedElementsOperations/selects.js
  cypress/support/pages/catalog/products/productsListPage.js
Labels: run e2e

#3215 Fix some vulnerabilities reported by `npm audit`
  package-lock.json
  package.json
Labels: run e2e

#3426 Migrate to refresh token
  cypress/support/customCommands/user/index.js
  package-lock.json
  package.json
Labels: run e2e
