Repository saleor/saleor-dashboard, pull requests merged in 2023-04, with the labels that each got.

#3412 Select filter presets
  locale/defaultMessages.json
  package-lock.json
  package.json
  src/components/ActionDialog/ActionDialog.tsx
  src/components/ActionDialog/DialogButtons.tsx
  src/components/AppLayout/AppLayout.tsx
  src/components/AppLayout/FilterBar/FilterButton.tsx
  src/components/AppLayout/FilterBar/index.ts
  src/components/AppLayout/ListFilters/ListFilters.tsx
  src/components/AppLayout/ListFilters/components/FiltersSelect.tsx
  src/components/AppLayout/ListFilters/components/SearchInput.tsx
  src/components/AppLayout/ListFilters/index.ts
  src/components/AppLayout/ListFilters/utils.test.ts
  src/components/AppLayout/ListFilters/utils.ts
  src/components/AppLayout/TopNav/TopNav.tsx
  src/components/BackButton.tsx
  src/components/Datagrid/Datagrid.tsx
  src/components/DeleteFilterTabDialog/DeleteFilterTabDialog.tsx
  src/components/Filter/Filter.tsx
  src/components/Filter/reducer.ts
  src/components/Filter/useFilter.ts
  src/components/Filter/utils.ts
  src/components/FilterPresetsSelect/FilterPresetItem.tsx
  src/components/FilterPresetsSelect/FilterPresetsSelect.tsx
  src/components/FilterPresetsSelect/index.ts
  src/components/FilterPresetsSelect/messages.ts
  src/components/FilterPresetsSelect/utils.ts
  src/components/SaveFilterTabDialog/SaveFilterTabDialog.tsx
  src/hooks/useSortRedirects.ts
  src/intl.ts
  src/orders/components/OrderListPage/OrderListPage.stories.tsx
  src/orders/components/OrderListPage/filters.ts
  src/orders/views/OrderList/filters.test.ts
  src/orders/views/OrderList/filters.ts
  src/products/components/ProductListDatagrid/ProductListDatagrid.tsx
  src/products/components/ProductListPage/ProductListPage.stories.tsx
  src/products/components/ProductListPage/ProductListPage.tsx
  src/products/components/ProductListPage/filters.ts
  src/products/urls.ts
  src/products/views/ProductList/ProductList.tsx
  src/products/views/ProductList/filters.ts
  src/products/views/ProductList/utils.test.ts
  src/products/views/ProductList/utils.ts
  src/types.ts
  src/utils/filters/filters.ts
  src/utils/filters/qs.test.ts
  src/utils/filters/qs.ts
  src/utils/filters/storage.ts
  src/utils/handlers/filterHandlers.ts
Labels: run e2e

#3516 Allow refreshing proper token based on token owner
  package-lock.json
  package.json
Labels: do not merge

#3522 Pin macaw-ui version
  package-lock.json
  package.json
Labels: run e2e

#3505 Increase dots
  src/components/StatusDot/StatusDot.tsx
Labels: products

#3276 Static datagrid in order view
  locale/defaultMessages.json
  package-lock.json
  package.json
  src/collections/components/CollectionList/CollectionList.tsx
  src/components/ChannelsAvailabilityDropdown/ChannelsAvailabilityDropdown.tsx
  src/components/ChannelsAvailabilityMenuContent/ChannelsAvailabilityMenuContent.tsx
  src/components/Datagrid/Datagrid.tsx
  src/components/Datagrid/customCells/DropdownCell.tsx
  src/components/Datagrid/customCells/MoneyCell.tsx
  src/components/Datagrid/customCells/NumberCell.tsx
  src/components/Datagrid/customCells/ThumbnailCell.tsx
  src/components/Datagrid/customCells/cells.ts
  src/components/Datagrid/customCells/useCustomCellRenderers.ts
  src/components/Datagrid/hooks/useColumnsDefault.ts
  src/components/Datagrid/hooks/useEmptyColumn.ts
  src/components/Money/Money.tsx
  src/components/Pill/Pill.tsx
  src/components/Pill/index.ts
  src/components/PreviewPill/PreviewPill.tsx
  src/custom-apps/components/WebhookEvents/WebhookEvents.tsx
  src/custom-apps/components/WebhookInfo/WebhookInfo.tsx
  src/custom-apps/components/WebhooksList/WebhooksList.tsx
  src/customers/components/CustomerOrders/CustomerOrders.tsx
  src/giftCards/components/GiftCardStatusChip/GiftCardStatusChip.tsx
  src/misc.ts
  src/orders/components/OrderDetailsPage/Title.tsx
  src/orders/components/OrderGrantedRefunds/OrderGrantedRefunds.tsx
  src/orders/components/OrderList/OrderList.tsx
  src/orders/components/OrderListDatagrid/OrderListDatagrid.tsx
  src/orders/components/OrderListDatagrid/datagrid.ts
  src/orders/components/OrderListDatagrid/index.ts
  src/orders/components/OrderListDatagrid/messages.ts
  src/orders/components/OrderListDatagrid/uitls.test.ts
  src/orders/components/OrderListDatagrid/utils.ts
  src/orders/components/OrderListPage/OrderListPage.stories.tsx
  src/orders/components/OrderListPage/OrderListPage.tsx
  src/orders/components/OrderPayment/OrderPayment.tsx
  src/orders/components/OrderPaymentOrTransaction/OrderPaymentOrTransaction.test.tsx
  src/orders/components/OrderPaymentSummaryCard/OrderPaymentSummaryCard.tsx
  src/orders/components/OrderTransaction/components/TransactionEvents/components/EventStatus.tsx
  src/orders/messages.ts
  src/orders/views/OrderList/OrderList.tsx
  src/orders/views/OrderList/filters.ts
  src/orders/views/OrderList/sort.ts
  src/pages/components/PageList/PageList.tsx
  src/plugins/components/PluginsList/PluginAvailabilityStatus.tsx
  src/plugins/components/PluginsList/PluginAvailabilityStatusPopup/GlobalConfigPluginPopupBody.tsx
  src/products/components/ProductListDatagrid/ProductListDatagrid.tsx
  src/products/components/ProductListDatagrid/utils.ts
  src/products/components/ProductListTiles/ProductListTiles.tsx
  testUtils/wrapper.tsx
Labels: run e2e

#3530 Add SWC to optional deps
  package-lock.json
  package.json
Labels: run e2e

#3504 Overwrite variables for GraphQL playground
  src/components/DevModePanel/DevModePanel.tsx
  src/components/GraphiQL/GraphiQL.tsx
Labels: playground

#3548 Fix Datagrid links regression
  src/components/Datagrid/Datagrid.tsx
  src/orders/components/OrderListDatagrid/OrderListDatagrid.tsx
  src/orders/components/OrderListPage/OrderListPage.tsx
  src/products/components/ProductListDatagrid/ProductListDatagrid.tsx
  src/products/components/ProductListPage/ProductListPage.tsx
Labels: bug, datagrid

#3584 fix: remove semver logic from navigator & autohide banner
  package-lock.json
  package.json
  src/components/Navigator/Navigator.tsx
Labels: run e2e
