Repository saleor/saleor-dashboard, pull requests merged in 2023-01, with the labels that each got.

#2905 E2E fixes after countryArea changes
  cypress/elements/shared/addressForm.js
  cypress/fixtures/addresses.json
  cypress/support/customCommands/sharedElementsOperations/addressForm.js
Labels: run e2e, tests

#2936 Bump macaw-ui to 0.7.2
  package-lock.json
  package.json
Labels: dependencies

#2924 Fix tests for SKU
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/e2e/products/productsWithoutSku/updatingProductsWithoutSku.js
  cypress/support/api/requests/Product.js
  cypress/support/api/utils/products/productsUtils.js
  cypress/support/customCommands/sharedElementsOperations/selects.js
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: tests

#2942 Fix should be able to create price based shipping method
  cypress/elements/shipping/shipping-zone-details.js
  src/components/MultiAutocompleteSelectField/MultiAutocompleteSelectField.tsx
  src/shipping/components/ShippingZoneSettingsCard/ChannelsSection.tsx
Labels: tests

#2950 2868 fix should make a refund 2107
  cypress/e2e/orders/orders.js
  cypress/support/api/requests/Product.js
  cypress/support/api/requests/ShippingMethod.js
  cypress/support/api/requests/Taxes.js
  cypress/support/api/utils/products/productsUtils.js
  cypress/support/api/utils/shippingUtils.js
  cypress/support/api/utils/taxesUtils.js
Labels: run e2e, tests

#2952 Fix for client cleanup function
  cypress/support/api/requests/Customer.js
Labels: tests

#2954 restore saving variant in fillUpVariantDetails
  cypress/support/pages/catalog/products/VariantsPage.js
Labels: run e2e, tests

#2938 Hide toolbar in app page
  locale/defaultMessages.json
  src/apps/components/AppPage/AppPage.stories.tsx
  src/apps/components/AppPage/AppPage.tsx
  src/apps/components/AppPage/styles.ts
  src/apps/components/AppPage/useSettingsBreadcrumbs.ts
  src/apps/views/App/App.tsx
  src/apps/views/AppSettings/AppSettings.tsx
  src/components/AppLayout/AppLayout.tsx
  src/components/AppLayout/styles.ts
Labels: Feature: Apps

#2969 Replace order line total calculation with API value
  src/components/Money/Money.tsx
  src/fragments/orders.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/orders/components/OrderDraftDetailsProducts/TableLine.test.tsx
  src/orders/components/OrderDraftDetailsProducts/TableLine.tsx
  src/orders/components/OrderDraftPage/storybook.utils.tsx
  src/orders/components/OrderProductsCardElements/OrderProductsTableRow.tsx
  src/orders/fixtures.ts
  src/orders/utils/data.test.ts
  src/products/components/OrderDiscountProviders/OrderDiscountProvider.tsx
  src/products/components/OrderDiscountProviders/OrderLineDiscountProvider.tsx
  src/products/components/OrderDiscountProviders/types.ts
Labels: bug

#2962 Fix test related to saving variant
  cypress/e2e/products/productsVariants.js
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/e2e/products/productsWithoutSku/updatingProductsWithoutSku.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/support/pages/catalog/products/VariantsPage.js
  src/products/components/ProductStocks/ProductStocks.tsx
Labels: run e2e, tests

#2917 Update tests check if all data created in before are correct
  cypress/e2e/apps.js
  cypress/e2e/catalog/categories.js
  cypress/e2e/catalog/collections.js
  cypress/e2e/catalog/giftCards/activateGiftCards.js
  cypress/e2e/catalog/giftCards/purchaseGiftCard.js
  cypress/e2e/checkout/clickAndCollect.js
  cypress/e2e/checkout/productWithoutShipping.js
  cypress/e2e/checkout/purchaseWithProductTypes.js
  cypress/e2e/checkout/stocksInCheckout.js
  cypress/e2e/configuration/attributes/attributeVariantSelection.js
  cypress/e2e/configuration/attributes/deleteAndUpdateContentAttribute.js
  cypress/e2e/configuration/channels/channels.js
  cypress/e2e/configuration/channels/inactiveChannel.js
  cypress/e2e/configuration/customer.js
  cypress/e2e/configuration/navigation.js
  cypress/e2e/configuration/plugins/adyen.js
  cypress/e2e/configuration/plugins/stripe.js
  cypress/e2e/configuration/productTypes/attributesInProduductTypes.js
  cypress/e2e/configuration/productTypes/deleteProductType.js
  cypress/e2e/configuration/shippingMethods/createShippingMethod.js
  cypress/e2e/configuration/shippingMethods/editShippingMethod.js
  cypress/e2e/configuration/shippingMethods/editShippingZone.js
  cypress/e2e/configuration/shippingMethods/postalCodes.js
  cypress/e2e/configuration/shippingMethods/shippingWeights/shippingWeightsLimits.js
  cypress/e2e/configuration/shippingMethods/shippingWeights/weightRecalculate.js
  cypress/e2e/configuration/siteSettings.js
  cypress/e2e/configuration/warehouses/warehouse.js
  cypress/e2e/customerRegistration.js
  cypress/e2e/discounts/sales/createSalesForProducts.js
  cypress/e2e/discounts/sales/createSalesForVariants.js
  cypress/e2e/discounts/sales/updateSales.js
  cypress/e2e/discounts/vouchers/createVouchers.js
  cypress/e2e/discounts/vouchers/createVouchersWithLimits.js
  cypress/e2e/discounts/vouchers/updateVouchers.js
  cypress/e2e/metadata.js
  cypress/e2e/orders/channelsInDraftOrders.js
  cypress/e2e/orders/draftOrders.js
  cypress/e2e/orders/manageStockReservation.js
  cypress/e2e/orders/orders.js
  cypress/e2e/pages/pages.js
  cypress/e2e/products/createProduct.js
  cypress/e2e/products/manageProducts/availableForPurchaseProducts.js
  cypress/e2e/products/manageProducts/publishedProducts.js
  cypress/e2e/products/manageProducts/visibleInListingsProducts.js
  cypress/e2e/products/productsList/filteringProducts.js
  cypress/e2e/products/productsList/sortingProducts.js
  cypress/e2e/products/productsVariants.js
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/e2e/products/productsWithoutSku/updatingProductsWithoutSku.js
  cypress/e2e/products/updatingProducts.js
  cypress/e2e/staffMembers.js
  cypress/e2e/translations.js
  cypress/support/customCommands/basicOperations/index.js
Labels: tests

#2985 Add the @allEnv tag to tests where it is missing
  cypress/e2e/configuration/plugins/adyen.js
  cypress/e2e/configuration/plugins/plugins.js
  cypress/e2e/configuration/plugins/stripe.js
  cypress/e2e/staffMembers.js
  cypress/e2e/translations.js
Labels: tests

#2945 Fix strict null checks in warehouses
  locale/defaultMessages.json
  src/hooks/usePaginator.ts
  src/misc.ts
  src/utils/handlers/filterHandlers.ts
  src/utils/limits.ts
  src/utils/maps.ts
  src/warehouses/components/WarehouseCreatePage/WarehouseCreatePage.stories.tsx
  src/warehouses/components/WarehouseDetailsPage/WarehouseDetailsPage.stories.tsx
  src/warehouses/components/WarehouseDetailsPage/WarehouseDetailsPage.tsx
  src/warehouses/components/WarehouseList/WarehouseList.tsx
  src/warehouses/components/WarehouseListPage/WarehouseListPage.tsx
  src/warehouses/components/WarehouseSettings/WarehouseSettings.tsx
  src/warehouses/components/WarehouseSettings/messages.ts
  src/warehouses/views/WarehouseCreate/WarehouseCreate.tsx
  src/warehouses/views/WarehouseDetails/WarehouseDetails.tsx
  src/warehouses/views/WarehouseList/WarehouseList.tsx
  src/warehouses/views/WarehouseList/sort.ts
Labels: maintenance

#3015 Fix failed night schedule tests
  cypress.config.js
  cypress/e2e/catalog/giftCards/activateGiftCards.js
  cypress/e2e/configuration/attributes/attributeVariantSelection.js
  cypress/e2e/customerRegistration.js
  cypress/e2e/discounts/sales/createSalesForProducts.js
  cypress/e2e/discounts/sales/createSalesForVariants.js
  cypress/e2e/discounts/sales/updateSales.js
  cypress/e2e/discounts/vouchers/createVouchers.js
  cypress/e2e/discounts/vouchers/updateVouchers.js
  cypress/e2e/products/productsVariants.js
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/elements/catalog/products/variants-selectors.js
  cypress/support/api/requests/Taxes.js
  cypress/support/api/utils/taxesUtils.js
  cypress/support/pages/catalog/products/VariantsPage.js
  cypress/support/pages/discounts/salesPage.js
Labels: tests

#2939 Fix test for creating free shipping voucher
  .github/workflows/approveAndMergeReleasePR.js
  cypress/e2e/configuration/attributes/attributeVariantSelection.js
  cypress/e2e/discounts/vouchers/createVouchers.js
  cypress/e2e/discounts/vouchers/updateVouchers.js
  cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
  cypress/e2e/staffMembers.js
  cypress/support/api/utils/taxesUtils.js
  src/components/AppLayout/AppLayout.tsx
  src/custom-apps/views/CustomAppWebhookDetails.tsx
  src/misc.ts
  src/new-apps/components/AppListPage/AppListPage.tsx
  src/new-apps/components/AppListPage/utils.test.ts
  src/new-apps/hooks/useActiveAppsInstallations.ts
  src/new-apps/utils.ts
  src/new-apps/views/AppList/AppList.tsx
  src/staff/views/StaffDetails.tsx
  src/taxes/pages/TaxClassesPage/TaxClassesPage.tsx
  src/utils/errors/common.ts
  src/utils/errors/index.ts
  src/utils/filters/filters.ts
  src/utils/handlers/filterHandlers.ts
  src/utils/maps.ts
  src/utils/menu/menu.ts
  src/utils/sort.ts
  src/warehouses/components/WarehouseCreatePage/WarehouseCreatePage.stories.tsx
  src/warehouses/components/WarehouseDetailsPage/WarehouseDetailsPage.stories.tsx
  src/warehouses/components/WarehouseDetailsPage/WarehouseDetailsPage.tsx
  src/warehouses/views/WarehouseList/sort.ts
  testUtils/globalSetup.ts
Labels: tests

#3041 Fix release flow job for minor versions
  .github/workflows/getEnvironmentVariables.js
Labels: tests

#3005 Fix strict null check in attributes
  src/attributes/components/AttributeDetails/AttributeDetails.tsx
  src/attributes/components/AttributeDetails/NumericUnits.tsx
  src/attributes/components/AttributeList/AttributeList.tsx
  src/attributes/components/AttributePage/AttributePage.tsx
  src/attributes/components/AttributeSwatchField/AttributeSwatchField.tsx
  src/attributes/components/AttributeValues/AttributeValues.tsx
  src/attributes/errors.ts
  src/attributes/fixtures.ts
  src/attributes/utils/data.ts
  src/attributes/utils/handlers.test.ts
  src/attributes/utils/handlers.ts
  src/attributes/views/AttributeCreate/AttributeCreate.tsx
  src/attributes/views/AttributeDetails/AttributeDetails.tsx
  src/attributes/views/AttributeList/AttributeList.tsx
  src/attributes/views/AttributeList/filters.ts
  src/attributes/views/AttributeList/sort.ts
  src/misc.ts
Labels: run e2e, maintenance

#3055 Fix test should not be able to create staff member with not unique email. TC: SALEOR_3508
  cypress/e2e/staffMembers.js
  cypress/elements/shared/button-selectors.js
  cypress/elements/staffMembers/inviteStaffMemberForm.js
  src/staff/components/StaffAddMemberDialog/StaffAddMemberDialog.tsx
  src/staff/components/StaffAddMemberDialog/types.ts
Labels: tests
