Repository saleor/saleor-dashboard, pull requests merged in 2023-10, with the labels that each got.

#4287 Fix fetching private metadata for Order only when staff userr
  .changeset/tall-windows-lie.md
  .husky/pre-commit
  src/fragments/orders.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/orders/components/OrderMetadataDialog/OrderMetadataDialog.tsx
  src/orders/components/OrderSendRefundPage/components/TransactionCard.tsx
  src/orders/fixtures.ts
  src/orders/mutations.ts
  src/orders/queries.ts
  src/orders/utils/data.test.ts
  src/orders/views/OrderDetails/OrderDetails.tsx
  src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
  src/orders/views/OrderDetails/OrderNormalDetails/index.tsx
  src/orders/views/OrderDetails/OrderUnconfirmedDetails/index.tsx
  src/orders/views/OrderFulfill/OrderFulfill.tsx
  src/orders/views/OrderRefund/OrderRefund.tsx
  src/orders/views/OrderReturn/OrderReturn.tsx
  src/orders/views/OrderSendRefund/OrderSendRefund.tsx
  src/products/components/OrderDiscountProviders/OrderDiscountProvider.tsx
  src/products/components/OrderDiscountProviders/OrderLineDiscountProvider.tsx
Labels: run e2e

#4282 Update usage of defaultTransactionFlowStrategy after migrating it to paymentSettings
  .changeset/spotty-bananas-live.md
  cypress/support/api/requests/Channels.js
  introspection.json
  schema.graphql
  src/channels/fixtures.ts
  src/channels/pages/ChannelDetailsPage/ChannelDetailsPage.tsx
  src/channels/views/ChannelDetails/ChannelDetails.tsx
  src/fragments/channels.ts
  src/graphql/hooks.generated.ts
  src/graphql/typePolicies.generated.ts
  src/graphql/types.generated.ts
Labels: run e2e

#4209 Migrate product variant page
  .changeset/honest-toys-decide.md
  cypress/support/pages/catalog/products/VariantsPage.js
  locale/defaultMessages.json
  src/components/Datagrid/customCells/Money/MoneyCell.tsx
  src/components/Divider/Divider.tsx
  src/components/Divider/index.ts
  src/components/MediaTile/MediaTile.tsx
  src/components/SortableTable/SortableHandle.tsx
  src/components/TableCellAvatar/Avatar.tsx
  src/components/TableCellAvatar/TableCellAvatar.tsx
  src/fragments/products.ts
  src/graphql/hooks.generated.ts
  src/orders/components/OrderSendRefundPage/components/TransactionCard.tsx
  src/orders/views/OrderDetails/OrderDetails.tsx
  src/products/components/ProductStocks/ProductStocks.tsx
  src/products/components/ProductStocks/messages.ts
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/AvailabilityCard.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/CardSkeleton.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/ChannelsList.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/ChannelsListItem.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/CreateVariantTitle.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/NotAvailable.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/VariantDetailsChannelsAvailabilityCardContainer.tsx
  src/products/components/ProductVariantChannels/ChannelsAvailabilityCard/index.tsx
  src/products/components/ProductVariantCheckoutSettings/ProductVariantCheckoutSettings.tsx
  src/products/components/ProductVariantCheckoutSettings/messages.ts
  src/products/components/ProductVariantCreatePage/ProductVariantCreatePage.tsx
  src/products/components/ProductVariantMedia/ProductVariantMedia.tsx
  src/products/components/ProductVariantName/ProductVariantName.tsx
  src/products/components/ProductVariantNavigation/ProductVariantNavigation.tsx
  src/products/components/ProductVariantNavigation/components/ImagePlaceholder.tsx
  src/products/components/ProductVariantNavigation/components/SortableContainer.tsx
  src/products/components/ProductVariantNavigation/styles.ts
  src/products/components/ProductVariantPage/ProductVariantPage.tsx
  src/products/components/ProductVariantPrice/ProductVariantPrice.tsx
  src/products/components/ProductVariantSetDefault/ProductVariantSetDefault.tsx
Labels: run chromatic

#4306 Make checkbox visible in datagrid
  .changeset/odd-pants-know.md
  package-lock.json
  package.json
  src/attributes/components/AttributeListDatagrid/AttributeListDatagrid.tsx
  src/categories/components/CategoryListDatagrid/CategoryListDatagrid.tsx
  src/categories/components/CategoryProductListDatagrid/CategoryProductListDatagrid.tsx
  src/collections/components/CollectionListDatagrid/CollectionListDatagrid.tsx
  src/customers/components/CustomerListDatagrid/CustomerListDatagrid.tsx
  src/discounts/components/SaleListDatagrid/SaleListDatagrid.tsx
  src/discounts/components/VoucherListDatagrid/VoucherListDatagrid.tsx
  src/giftCards/GiftCardsList/GiftCardsListDatagrid/GiftCardsListDatagrid.tsx
  src/orders/components/OrderDraftListDatagrid/OrderDraftListDatagrid.tsx
  src/pages/components/PageListDatagrid/PageListDatagrid.tsx
  src/products/components/ProductListDatagrid/ProductListDatagrid.tsx
  src/shipping/components/ShippingZonesListDatagrid/ShippingZonesListDatagrid.tsx
Labels: run e2e, run chromatic

#4309 Fix some errors regarding reading property of undefined
  .changeset/fifty-trains-invite.md
  src/products/views/ProductCreate/handlers.ts
  src/products/views/ProductUpdate/handlers/useProductUpdateHandler.ts
  src/utils/handlers/metadataCreateHandler.ts
Labels: run e2e

#4310 Fix storybook-chromatic-main.yml
  .changeset/fluffy-buckets-tell.md
  .github/workflows/storybook-chromatic-main.yml
Labels: run chromatic

#4329 Fix assigning products to collection
  .changeset/spotty-files-dance.md
  src/collections/views/CollectionDetails.tsx
Labels: run e2e
