Repository saleor/saleor-dashboard, pull requests merged in 2025-07, with the labels that each got.

#5689 fix: typo in image upload error message
  .changeset/little-kings-brake.md
  locale/defaultMessages.json
  src/intl.ts
Labels: bug

#5694 Fix AWS credentials for 3.20 branch
  .github/workflows/deploy-and-run-cypress.yml
  .github/workflows/deploy-cloud.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-master-staging.yaml
  .github/workflows/deploy-staging-and-prepare-release.yaml
  .github/workflows/pr-automation.yml
  .github/workflows/test-env-cleanup.yml
Labels: skip changeset

#5701 ENG-294: Refactor Products page query handling
  playwright/pages/discountsPage.ts
  playwright/pages/extensionsPage.ts
  playwright/tests/apps.spec.ts
  playwright/tests/channels.spec.ts
  playwright/tests/singlePermissions/extensions.spec.ts
  playwright/tests/singlePermissions/plugins.spec.ts
  playwright/tests/singlePermissions/readonlyExtensionsAccess.spec.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/FilterQueryVarsBuilderResolver.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/FilterQueryVarsBuilderResolver.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/FiltersQueryBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/FiltersQueryBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/index.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/AttributeQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/AttributeQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/BaseMappableQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/DefaultQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/ProductTypeQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/ProductTypeQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/StaticBooleanQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/StaticBooleanQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/StaticQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/StaticQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/index.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/types.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/types.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/utils.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/utils.ts
  src/components/ConditionalFilter/queryVariables.ts
  src/components/ConditionalFilter/queryVarsBuilders/definitions/AttributeDefinition.ts
Labels: run pw-e2e, skip changeset

#5711 Fix - remove unused file
  src/components/ConditionalFilter/queryVarsBuilders/definitions/AttributeDefinition.ts
Labels: skip changeset

#5714 Fixes for global search
  src/components/Sidebar/shortcuts/useShortcuts.tsx
  src/icons/TerminalIcon.tsx
  src/search/SearchShortcut.tsx
  src/search/resultsTable/CommonCells.tsx
  src/search/resultsTable/OrderItem.tsx
  src/search/resultsTable/ResultItem.tsx
  src/search/resultsTable/ResultsTable.tsx
  src/search/resultsTable/prepareResults.ts
Labels: skip changeset

#5716 Added deprecated comments to Form
  src/components/Form/ExitFormDialog.tsx
  src/components/Form/Form.tsx
  src/components/Form/useExitFormDialog.ts
  src/components/Form/useExitFormDialogProvider.tsx
  src/hooks/useForm/index.ts
  src/hooks/useForm/useChangedData.ts
  src/hooks/useFormset.ts
Labels: skip changeset

#5722 Remove extensions dead code
  src/extensions/views/ExploreExtensions/components/ExploreExtensionsActions.tsx
  src/extensions/views/InstalledExtensions/InstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/components/AddExtensionDropdown/AddExtensionDropdown.test.tsx
  src/extensions/views/InstalledExtensions/components/AddExtensionDropdown/AddExtensionDropdown.tsx
Labels: skip changeset

#5700 ENG-294: Refactor remaining pages to use new FilterDefinition
  src/collections/views/CollectionList/CollectionList.tsx
  src/components/ConditionalFilter/FiltersQueryBuilder/FilterQueryVarsBuilderResolver.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/AttributeTypeQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/AttributeTypeQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/CollectionPublishedQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/CollectionPublishedQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/CustomerNumberOfOrdersQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/CustomerNumberOfOrdersQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/MetadataQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/MetadataQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/SlugChannelQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/SlugChannelQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/StaffMemberStatusQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/StaffMemberStatusQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/VoucherStatusQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/VoucherStatusQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/VoucherTimesUsedQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/VoucherTimesUsedQueryVarsBuilder.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/index.ts
  src/components/ConditionalFilter/queryVariables.test.ts
  src/components/ConditionalFilter/queryVariables.ts
  src/discounts/views/VoucherList/VoucherList.tsx
  src/orders/views/OrderList/filters.ts
Labels: run pw-e2e, skip changeset

#5723 Add skip changeset label to update schema workflow
  .github/workflows/update-schema.yml
Labels: skip changeset

#5734 make vite.config.js typed
  .eslintrc.json
  vite.config.js
Labels: skip changeset

#5742 Improve some ts-strict-ignore instances
  src/hooks/useOnSetDefaultVariant.ts
  src/orders/components/OrderGrantRefundPage/OrderGrantRefundPage.tsx
  src/orders/components/OrderGrantRefundPage/components/ShippingInluded.tsx
  src/orders/components/OrderGrantRefundPage/form.ts
  src/orders/components/OrderTransaction/components/TransactionEvents/components/EventCreatedBy.test.tsx
  src/orders/components/OrderTransaction/components/TransactionEvents/components/EventItem.test.tsx
  src/orders/views/OrderGrantRefund/OrderGrantRefund.tsx
  src/staff/utils.ts
Labels: skip changeset

#5745 Conditionally show translate button
  src/attributes/components/AttributePage/AttributePage.tsx
  src/categories/components/CategoryUpdatePage/CategoryUpdatePage.tsx
  src/collections/components/CollectionDetailsPage/CollectionDetailsPage.tsx
  src/discounts/components/VoucherDetailsPage/VoucherDetailsPage.tsx
  src/modeling/components/PageDetailsPage/PageDetailsPage.tsx
  src/products/components/ProductUpdatePage/ProductUpdatePage.tsx
  src/products/components/ProductVariantPage/ProductVariantPage.tsx
  src/shipping/components/ShippingZoneDetailsPage/ShippingZoneDetailsPage.tsx
  src/structures/components/MenuDetailsPage/MenuDetailsPage.tsx
  src/structures/components/MenuItems/MenuItems.tsx
  src/structures/components/MenuItemsSortableTree/MenuItemsSortableTree.tsx
  src/structures/components/MenuItemsSortableTree/MenuItemsSortableTreeItem.tsx
  src/structures/views/MenuDetails/index.tsx
Labels: skip changeset, skip macaw migration check

#5709 [3.21] Fix failing e2e tests
  playwright/pages/extensionsPage.ts
  playwright/tests/apps.spec.ts
  playwright/tests/channels.spec.ts
  playwright/tests/singlePermissions/extensions.spec.ts
  playwright/tests/singlePermissions/plugins.spec.ts
  playwright/tests/singlePermissions/readonlyExtensionsAccess.spec.ts
Labels: stale, run pw-e2e, skip changeset

#5750 [3.21] Fix extension tests on 3.21 branch
  package-lock.json
  playwright/pages/appInstallationPage.ts
  playwright/pages/extensionsPage.ts
  playwright/tests/apps.spec.ts
  playwright/tests/singlePermissions/plugins.spec.ts
  src/extensions/views/InstallCustomExtension/components/InstallCustomExtensionFromForm/InstallCustomExtensionFromForm.tsx
  src/extensions/views/InstallCustomExtension/components/InstallCustomExtensionFromUrl/InstallCustomExtensionFromUrl.tsx
  src/extensions/views/InstallCustomExtension/components/ManifestUrlForm/ManifestUrlForm.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
Labels: run pw-e2e, skip changeset, skip macaw migration check

#5732 Command menu implementation
  .changeset/nice-snakes-teach.md
  .knip.json
  groupBy.d.ts
  locale/defaultMessages.json
  package-lock.json
  package.json
  src/components/NavigatorSearch/Actions.tsx
  src/components/NavigatorSearch/CommandContent.tsx
  src/components/NavigatorSearch/NavigatorSearch.tsx
  src/components/NavigatorSearch/NavigatorSearchInput.tsx
  src/components/NavigatorSearch/ResourcesTable.tsx
  src/components/NavigatorSearch/modes/catalog.test.ts
  src/components/NavigatorSearch/modes/catalog.ts
  src/components/NavigatorSearch/modes/commands/actions.test.ts
  src/components/NavigatorSearch/modes/commands/actions.ts
  src/components/NavigatorSearch/modes/commands/index.ts
  src/components/NavigatorSearch/modes/customers.ts
  src/components/NavigatorSearch/modes/default/default.ts
  src/components/NavigatorSearch/modes/default/index.ts
  src/components/NavigatorSearch/modes/default/views.ts
  src/components/NavigatorSearch/modes/help.ts
  src/components/NavigatorSearch/modes/index.ts
  src/components/NavigatorSearch/modes/labels.tsx
  src/components/NavigatorSearch/modes/messages.ts
  src/components/NavigatorSearch/modes/orders.ts
  src/components/NavigatorSearch/modes/types.ts
  src/components/NavigatorSearch/modes/utils.ts
  src/components/NavigatorSearch/queries.ts
  src/components/NavigatorSearch/queries/queries.ts
  src/components/NavigatorSearch/queries/useCatalogSearch.ts
  src/components/NavigatorSearch/queries/useQuickOrderSearch.test.ts
  src/components/NavigatorSearch/queries/useQuickOrderSearch.ts
  src/components/NavigatorSearch/useActionItems.test.ts
  src/components/NavigatorSearch/useActionItems.ts
  src/components/NavigatorSearch/useActionTriggers.tsx
  src/components/NavigatorSearch/useCommandMenuInput.ts
  src/components/NavigatorSearch/useKeyboardNavigation.test.ts
  src/components/NavigatorSearch/useKeyboardNavigation.ts
  src/components/NavigatorSearch/useQuickSearch.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/index.css
  src/search/index.tsx
  src/search/resultsTable/CategoryItem.tsx
  src/search/resultsTable/CollectionItem.tsx
  src/search/resultsTable/CommonCells.tsx
  src/search/resultsTable/ListSkeleton.tsx
  src/search/resultsTable/ModelItem.tsx
  src/search/resultsTable/ModelTypeItem.tsx
  src/search/resultsTable/OrderItem.tsx
  src/search/resultsTable/ProductItem.tsx
  src/search/resultsTable/ResultsList.tsx
  src/search/resultsTable/ResultsTable.tsx
  src/search/resultsTable/VariantItem.tsx
  src/search/urls.ts
  src/search/useSearchCriteria.ts
  testUtils/setup.ts
Labels: run pw-e2e

#5752 [3.21] Fix test assertion in app name
  playwright/tests/apps.spec.ts
Labels: skip changeset, skip macaw migration check
