Repository saleor/saleor-dashboard, pull requests merged in 2025-03, with the labels that each got.

#5446 Fix date issue with app alerts
  .changeset/warm-apes-wash.md
  src/apps/components/AppAlerts/useAppsAlert.ts
  src/apps/components/AppAlerts/useAppsFailedDeliveries.test.ts
  src/apps/components/AppAlerts/useAppsFailedDeliveries.ts
  src/apps/components/AppAlerts/utils.ts
Labels: run pw-e2e

#5441 Fix voucher validation when discount type is shipping
  .changeset/two-waves-tell.md
  src/channels/utils.ts
  src/discounts/data.ts
  src/discounts/handlers.test.ts
  src/discounts/handlers.ts
Labels: run pw-e2e

#5450 Handle / in nginx config
  .changeset/wicked-panthers-pay.md
  nginx/default.conf
Labels: run pw-e2e

#5451 Show latest date when webhook has failed deliveries
  .changeset/old-frogs-accept.md
  src/apps/components/AppAlerts/utils.test.ts
  src/apps/components/AppAlerts/utils.ts
  src/apps/fixtures.ts
  src/fragments/apps.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
Labels: run pw-e2e

#5452 Refresh shipping data after mutation
  .changeset/lazy-pillows-hammer.md
  src/fragments/shipping.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/shipping/mutations.ts
Labels: run pw-e2e

#5453 Fix app alert's date saving to metadata
  .changeset/plenty-beers-enjoy.md
  src/apps/components/AppAlerts/SidebarAppAlert.test.tsx
  src/apps/components/AppAlerts/SidebarAppAlert.tsx
  src/apps/components/AppAlerts/useAppsAlert.ts
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
Labels: run pw-e2e

#5440 Turn on app alerts in feature flags
  .changeset/young-doors-jog.md
  .featureFlags/app_alerts.md
  .featureFlags/generated.tsx
  .featureFlags/images/app-alerts.jpg
  locale/defaultMessages.json
  src/apps/components/AppAlerts/AppRowWebhookIssueAlert.tsx
  src/apps/components/AppAlerts/useAppsAlert.ts
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
Labels: do not merge, run pw-e2e

#5454 Show event delivery ID in app's details
  .changeset/loud-rice-rescue.md
  locale/defaultMessages.json
  src/apps/components/AppWebhooksDisplay/EventDeliveriesList.tsx
  src/apps/components/AppWebhooksDisplay/EventDeliveryItem.tsx
Labels: run pw-e2e

#5456 Fix app alert disappearing logic
  .changeset/eighty-pans-sparkle.md
  src/apps/components/AppAlerts/useSidebarDotState.test.ts
  src/apps/components/AppAlerts/useSidebarDotState.ts
Labels: run pw-e2e

#5458 OrderLine metadata form: reset form on close
  .changeset/yellow-cups-arrive.md
  src/orders/components/OrderMetadataDialog/OrderMetadataDialog.tsx
Labels: run pw-e2e

#5464 Fix blocking default event in StopPropagation
  .changeset/three-kangaroos-marry.md
  src/apps/components/InstalledAppListRow/InstalledAppListRow.tsx
  src/components/StopPropagation/StopPropagation.tsx
Labels: run pw-e2e

#5462 Set constant height for rows
  .changeset/heavy-adults-brush.md
  src/collections/components/CollectionProducts/ProductTableItem.tsx
Labels: run pw-e2e

#5461 fix discord link
  src/welcomePage/WelcomePageTilesContainer/links.ts
Labels: run pw-e2e, skip changeset

#5459 Cleanup 3.20.29
  .changeset/cuddly-eggs-flow.md
  .changeset/dry-queens-vanish.md
  .changeset/early-carpets-buy.md
  .changeset/eighty-pans-sparkle.md
  .changeset/friendly-actors-bow.md
  .changeset/hip-bobcats-fetch.md
  .changeset/khaki-melons-juggle.md
  .changeset/late-kangaroos-punch.md
  .changeset/lazy-pillows-hammer.md
  .changeset/lemon-shrimps-obey.md
  .changeset/loud-hats-dream.md
  .changeset/loud-rice-rescue.md
  .changeset/lucky-hornets-hide.md
  .changeset/modern-pianos-sneeze.md
  .changeset/odd-impalas-rule.md
  .changeset/old-frogs-accept.md
  .changeset/plenty-beers-enjoy.md
  .changeset/poor-files-travel.md
  .changeset/quiet-berries-smile.md
  .changeset/quiet-goats-wonder.md
  .changeset/silent-bikes-teach.md
  .changeset/thick-ravens-compare.md
  .changeset/two-waves-tell.md
  .changeset/warm-apes-wash.md
  .changeset/wicked-panthers-pay.md
  .changeset/yellow-cups-arrive.md
  .changeset/young-doors-jog.md
Labels: run pw-e2e, skip changeset

#5460 Fix image scaling
  .changeset/pretty-pianos-rush.md
  src/orders/components/OrderMetadataDialog/OrderLineDetails/VariantThumbnail.tsx
Labels: run pw-e2e

#5466 Order history event link a11y fix
  .changeset/fair-balloons-yell.md
  locale/defaultMessages.json
  src/components/Timeline/TimelineEventHeader.tsx
  src/giftCards/components/GiftCardCustomerCard/CustomerGiftCardsCard.tsx
  src/misc.ts
  src/orders/components/OrderHistory/ExtendedTimelineEvent.tsx
  src/orders/components/OrderHistory/LinkedTimelineEvent.tsx
  src/orders/components/OrderHistory/utils.tsx
Labels: run pw-e2e

#5467 Reset warehouse picker in order fulfillment
  .changeset/itchy-spies-beam.md
  src/orders/components/OrderChangeWarehouseDialog/OrderChangeWarehouseDialog.tsx
Labels: run pw-e2e

#5470 Fix flaky tests 77 78 79
  .changeset/rich-ears-act.md
  playwright/tests/orders.spec.ts
Labels: run pw-e2e

#5438 Update Node to v20 (part 1)
  .changeset/mighty-fishes-happen.md
  .nvmrc
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/components/Money/index.ts
  src/components/MoneyRange/utils.test.ts
Labels: run pw-e2e

#5475 Handle failed deliveries without any attempts
  .changeset/honest-squids-fry.md
  src/apps/components/AppAlerts/utils.test.ts
  src/apps/components/AppAlerts/utils.ts
Labels: run pw-e2e

#5478 Update Vitejs to latest
  .changeset/silver-months-hunt.md
  package-lock.json
  package.json
  vite.config.js
Labels: run pw-e2e

#5474 Fix quantity value in order details for returned items
  .changeset/two-squids-leave.md
  src/orders/components/OrderFulfilledProductsCard/OrderFulfilledProductsCard.tsx
Labels: run pw-e2e

#5477 Add sorting and use latest attempt date in event delivery
  .changeset/olive-coats-repeat.md
  locale/defaultMessages.json
  src/apps/components/AppAlerts/AppRowWebhookIssueAlert.tsx
  src/apps/components/AppWebhooksDisplay/AppWebhooksAttemptDetails.tsx
  src/apps/components/AppWebhooksDisplay/AppWebhooksDisplay.tsx
  src/apps/components/AppWebhooksDisplay/EventDeliveriesList.tsx
  src/apps/components/AppWebhooksDisplay/EventDeliveryItem.tsx
  src/apps/queries.ts
  src/components/EventTime/EventTime.tsx
  src/graphql/hooks.generated.ts
Labels: run pw-e2e

#5479 Extensions routes and menu setup under ff
  .changeset/stale-scissors-press.md
  .featureFlags/extensions.md
  .featureFlags/generated.tsx
  locale/defaultMessages.json
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
  src/extensions/index.tsx
  src/extensions/urls.ts
  src/index.tsx
  src/intl.ts
Labels: run pw-e2e

#5419 Test reporting 3.19
  .changeset/tender-rules-wave.md
  .github/actions/flaky-tests-report/action.yml
  .github/actions/flaky-tests-report/package-lock.json
  .github/actions/flaky-tests-report/package.json
  .github/actions/merge-pw-reports/action.yml
  .github/actions/prepare-api-variables/action.yml
  .github/actions/prepare-tests-variables/action.yml
  .github/actions/push-flaky-test-report/action.yml
  .github/actions/run-pw-tests/action.yml
  .github/workflows/pr-automation.yml
  .github/workflows/run-test-manual.yml
  .github/workflows/run-tests-on-release.yml
  package-lock.json
  package.json
  playwright.config.ts
Labels: run pw-e2e

#5489 Add password argument for manual and release workflows (3.19)
  .changeset/healthy-adults-jump.md
  .github/workflows/run-test-manual.yml
  .github/workflows/run-tests-on-release.yml
Labels: run pw-e2e

#5471 Prevent page reload on login page
  .changeset/slimy-points-begin.md
  src/auth/components/LoginPage/LoginPage.test.tsx
  src/auth/components/LoginPage/LoginPage.tsx
  src/auth/components/LoginPage/form.tsx
  src/auth/components/LoginPage/messages.ts
  src/auth/components/styles.ts
  src/auth/hooks/useAuthProvider.test.ts
  src/auth/hooks/useAuthProvider.ts
  src/auth/hooks/useAuthRedirection.ts
  src/auth/index.tsx
  src/auth/types.ts
Labels: run pw-e2e

#5481 Extensions explore page
  assets/images/check.svg
  assets/images/plugin.svg
  locale/defaultMessages.json
  src/colors.ts
  src/components/AppLayout/ContextualLinks/messages.ts
  src/components/AppLayout/ContextualLinks/useContextualLink.tsx
  src/components/AppLayout/ListFilters/components/SearchInput.tsx
  src/components/ButtonWithDropdown/ButtonWithDropdown.tsx
  src/extensions/components/ExploreExtensionsActions/ExploreExtensionsActions.tsx
  src/extensions/components/ExploreExtensionsActions/index.ts
  src/extensions/components/ExtenionItem/ExtenionItem.tsx
  src/extensions/components/ExtenionItem/ExtensionItem.test.tsx
  src/extensions/components/ExtenionItem/components/AppActions.tsx
  src/extensions/components/ExtenionItem/components/InstalledBadge.tsx
  src/extensions/components/ExtenionItem/components/PluginActions.tsx
  src/extensions/components/ExtenionItem/components/PluginWarning.tsx
  src/extensions/components/ExtenionItem/hooks/useExtension.test.tsx
  src/extensions/components/ExtenionItem/hooks/useExtension.tsx
  src/extensions/components/ExtenionItem/index.ts
  src/extensions/components/ExtensionsGroup/ExtensionsGroup.tsx
  src/extensions/components/ExtensionsGroup/index.ts
  src/extensions/components/ExtensionsHeader/ExtensionsHeader.tsx
  src/extensions/components/ExtensionsHeader/index.ts
  src/extensions/components/ExtensionsList/ExtensionsList.tsx
  src/extensions/components/ExtensionsList/index.ts
  src/extensions/hooks/useExploreExtenstions.ts
  src/extensions/index.tsx
  src/extensions/messages.ts
  src/extensions/types.ts
  src/extensions/views/ExploreExtensions.tsx
  src/links.ts
Labels: run pw-e2e, skip changeset

#5493 Adopt old apps to extensions page
  locale/defaultMessages.json
  src/apps/components/AppDetailsPage/Header.tsx
  src/apps/components/AppListPage/AppListPage.tsx
  src/apps/urls.ts
  src/apps/views/AppInstallView/AppInstallView.tsx
  src/apps/views/AppListView/AppListView.tsx
  src/extensions/components/ExtenionItem/components/AppActions.tsx
  src/extensions/components/ExtensionsList/ExtensionsList.tsx
  src/extensions/components/ExtensionsList/NoExtenstions.tsx
  src/extensions/hooks/useExploreExtenstions.ts
  src/extensions/hooks/useExtensionsFilter.test.ts
  src/extensions/hooks/useExtenstionsFilter.ts
  src/extensions/index.tsx
  src/extensions/types.ts
  src/extensions/views/ExploreExtensions.tsx
Labels: run pw-e2e, skip changeset

#5491 Sort webhooks in App details by latest attempt
  .changeset/fifty-beds-watch.md
  src/apps/components/AppWebhooksDisplay/utils.test.ts
  src/apps/components/AppWebhooksDisplay/utils.ts
Labels: run pw-e2e

#5496 Cleanup 3.20.32
  .changeset/dull-dolls-search.md
  .changeset/kind-starfishes-raise.md
  .changeset/olive-coats-repeat.md
  .changeset/silver-months-hunt.md
  .changeset/stale-scissors-press.md
  .changeset/two-squids-leave.md
Labels: run pw-e2e, skip changeset

#5426 Add flaky reporting for releases
  .changeset/young-waves-hammer.md
  .github/actions/flaky-tests-report/action.yml
  .github/actions/flaky-tests-report/package-lock.json
  .github/actions/flaky-tests-report/package.json
  .github/actions/merge-pw-reports/action.yml
  .github/actions/prepare-tests-variables/action.yml
  .github/workflows/run-test-manual-new.yml
  .github/workflows/run-test-manual.yml
  .github/workflows/run-tests-on-release.yml
Labels: run pw-e2e

#5494 Feed extensions page with data
  .env.template
  .github/workflows/deploy-cloud.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-master-staging.yaml
  .github/workflows/deploy-staging-and-prepare-release.yaml
  .github/workflows/pr-automation.yml
  assets/images/plugin.svg
  locale/defaultMessages.json
  src/apps/apps-routing.tsx
  src/apps/components/AppListPage/AppListPage.tsx
  src/apps/components/AppListPage/MissingAppsFooter.tsx
  src/apps/views/AppManageView/AppManageView.tsx
  src/components/Sidebar/menu/ItemGroup.tsx
  src/config.ts
  src/extensions/components/ExtenionItem/ExtenionItem.tsx
  src/extensions/components/ExtenionItem/ExtensionItem.test.tsx
  src/extensions/components/ExtenionItem/components/AppActions.tsx
  src/extensions/components/ExtenionItem/components/PluginWarning.tsx
  src/extensions/components/ExtenionItem/hooks/useExtension.test.tsx
  src/extensions/components/ExtenionItem/hooks/useExtension.tsx
  src/extensions/components/ExtensionsGroup/ExtensionsGroup.tsx
  src/extensions/components/ExtensionsList/ExtensionsList.tsx
  src/extensions/components/ExtensionsList/LoadingSkeleton.tsx
  src/extensions/hooks/useAppStoreExtenstions.ts
  src/extensions/hooks/useExploreExtenstions.ts
  src/extensions/hooks/useExtensionsFilter.test.ts
  src/extensions/hooks/useExtenstionsFilter.ts
  src/extensions/hooks/useInstalledExtenstions.ts
  src/extensions/index.tsx
  src/extensions/messages.ts
  src/extensions/queries.ts
  src/extensions/types.ts
  src/extensions/views/ExploreExtensions.tsx
  src/fragments/apps.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/index.html
  testUtils/setup.ts
  types.d.ts
  vite.config.js
Labels: run pw-e2e, skip changeset

#5498 Fix quantity field value source for unfulfilled order products
  .changeset/shiny-olives-pretend.md
  src/orders/components/OrderUnfulfilledProductsCard/OrderUnfulfilledProductsCard.tsx
  src/orders/components/OrderUnfulfilledProductsCard/utils.test.ts
  src/orders/components/OrderUnfulfilledProductsCard/utils.ts
Labels: run pw-e2e

#5501 update app-sdk to v1
  .changeset/hungry-goats-check.md
  package-lock.json
  package.json
Labels: run pw-e2e

#5503 Disable vite plugin for Knip
  .changeset/rude-moles-stare.md
  .knip.json
Labels: run pw-e2e

#5504 Extensions empty state
  locale/defaultMessages.json
  src/apps/apps-routing.tsx
  src/apps/components/AppListPage/AppListPage.tsx
  src/apps/components/AppListPage/messages.ts
  src/apps/components/InstalledAppList/InstalledAppList.tsx
  src/apps/urls.ts
  src/apps/views/AppManageView/AppManageView.tsx
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
  src/extensions/components/EmptyListState/EmptyInstalledList.tsx
  src/extensions/components/EmptyListState/EmptyListState.tsx
  src/extensions/components/EmptyListState/EmptySearchList.tsx
  src/extensions/components/EmptyListState/index.ts
  src/extensions/components/ExploreExtensionsActions.tsx
  src/extensions/components/ExploreExtensionsActions/index.ts
  src/extensions/components/ExtensionsGroup.tsx
  src/extensions/components/ExtensionsGroup/index.ts
  src/extensions/components/ExtensionsHeader.tsx
  src/extensions/components/ExtensionsHeader/index.ts
  src/extensions/components/ExtensionsList/ExtensionsList.tsx
  src/extensions/components/ExtensionsList/NoExtenstions.tsx
  src/extensions/index.tsx
  src/extensions/messages.ts
  src/extensions/urls.ts
  src/extensions/views/ExploreExtensions.tsx
Labels: run pw-e2e, skip changeset

#5506 Extensions install buttons permission check
  src/apps/components/AppListPage/AppListPage.tsx
  src/apps/components/AppListPage/messages.ts
  src/extensions/components/ExtenionItem/ExtensionItem.test.tsx
  src/extensions/components/ExtenionItem/components/AppActions.tsx
  src/extensions/components/ExtenionItem/components/AppInstallButton.tsx
  src/extensions/components/ExtenionItem/hooks/useExtension.test.tsx
  src/extensions/components/RequestExtensionsButton.tsx
  src/extensions/messages.ts
  src/extensions/views/ExploreExtensions.tsx
Labels: run pw-e2e, skip changeset

#5508 Extensions: fix install button type and place of alert in menu
  src/components/Sidebar/menu/ItemGroup.tsx
  src/extensions/components/ExtenionItem/components/AppInstallButton.tsx
Labels: run pw-e2e, skip changeset

#5495 Search for product variants by SKU in quick search, show media
  .changeset/sharp-kangaroos-retire.md
  locale/defaultMessages.json
  src/components/NavigatorSearch/NavigatorSearch.tsx
  src/components/NavigatorSearch/NavigatorSearchSection.tsx
  src/components/NavigatorSearch/NavigatorThumbnail.tsx
  src/components/NavigatorSearch/modes/catalog.test.ts
  src/components/NavigatorSearch/modes/catalog.ts
  src/components/NavigatorSearch/modes/commands/actions.ts
  src/components/NavigatorSearch/modes/customers.ts
  src/components/NavigatorSearch/modes/default/views.ts
  src/components/NavigatorSearch/modes/help.ts
  src/components/NavigatorSearch/modes/labels.tsx
  src/components/NavigatorSearch/modes/messages.ts
  src/components/NavigatorSearch/modes/orders.ts
  src/components/NavigatorSearch/queries/queries.ts
  src/components/NavigatorSearch/types.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/misc.ts
Labels: run pw-e2e

#5505 Add "Overcharged" status to orders
  .changeset/little-pandas-travel.md
  locale/defaultMessages.json
  src/customers/components/CustomerOrders/CustomerOrders.tsx
  src/customers/fixtures.ts
  src/customers/queries.ts
  src/fragments/orders.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/misc.ts
  src/orders/components/OrderListDatagrid/datagrid.test.ts
  src/orders/components/OrderListDatagrid/datagrid.ts
  src/orders/components/OrderPayment/OrderPayment.tsx
  src/orders/components/OrderPaymentSummaryCard/OrderPaymentSummaryCard.tsx
  src/orders/components/OrderPaymentSummaryCard/components/OrderPaymentStatusPill.test.tsx
  src/orders/components/OrderPaymentSummaryCard/components/OrderPaymentStatusPill.tsx
  src/orders/fixtures.ts
  src/orders/queries.ts
Labels: run pw-e2e

#5502 Extensions feature flag preview
  .changeset/cyan-spoons-clap.md
  .env.template
  .featureFlags/extensions.md
  .featureFlags/generated.tsx
  .featureFlags/images/extensions.png
  Dockerfile
  docs/configuration.md
  docs/docker.md
  nginx/replace-env-vars.sh
Labels: run pw-e2e, skip changeset

#5509 Extensions: unit and components tests
  src/extensions/components/EmptyListState/EmptyListState.tsx
  src/extensions/components/ExtenionItem/ExtensionItem.test.tsx
  src/extensions/components/ExtenionItem/components/AppActions/AppActions.test.tsx
  src/extensions/components/ExtenionItem/components/AppActions/AppActions.tsx
  src/extensions/components/ExtenionItem/components/AppActions/index.ts
  src/extensions/components/ExtenionItem/components/AppInstallButton/AppInstallButton.test.tsx
  src/extensions/components/ExtenionItem/components/AppInstallButton/AppInstallButton.tsx
  src/extensions/components/ExtenionItem/components/AppInstallButton/index.ts
  src/extensions/components/ExtenionItem/hooks/useExtension.test.tsx
  src/extensions/components/ExtensionsList/ExtensionsList.test.tsx
  src/extensions/components/ExtensionsList/LoadingSkeleton.tsx
  src/extensions/hooks/useAppStoreExtensions.test.ts
  src/extensions/hooks/useAppStoreExtensions.ts
  src/extensions/hooks/useExploreExtensions.test.ts
  src/extensions/hooks/useExploreExtensions.ts
  src/extensions/hooks/useInstalledExtensions.ts
  src/extensions/views/ExploreExtensions.tsx
Labels: run pw-e2e, skip changeset

#5513 Extesnions: update e2e tests and turn on feture flag
  .featureFlags/extensions.md
  .featureFlags/generated.tsx
  playwright/data/url.ts
  playwright/pages/extensionsPage.ts
  playwright/pages/mainMenuPage.ts
  playwright/tests/apps.spec.ts
  playwright/tests/singlePermissions/extensions.spec.ts
  playwright/tests/singlePermissions/readonlyExtensionsAccess.spec.ts
  src/extensions/components/ExtensionsList/ExtensionsList.tsx
Labels: run pw-e2e, skip changeset

#5514 Cleanup changesets 3.20.34
  .changeset/cyan-spoons-clap.md
  .changeset/early-dogs-hammer.md
  .changeset/hungry-goats-check.md
  .changeset/little-pandas-travel.md
  .changeset/orange-chairs-move.md
  .changeset/rude-moles-stare.md
  .changeset/sharp-kangaroos-retire.md
  .changeset/shiny-olives-pretend.md
  .changeset/young-waves-hammer.md
Labels: skip changeset
