Repository saleor/saleor-dashboard, pull requests merged in 2025-04, with the labels that each got.

#5516 Improve tracking number and warehouse alignment in order view
  .changeset/happy-singers-sip.md
  src/orders/components/OrderFulfilledProductsCard/ExtraInfoLines.tsx
Labels: run pw-e2e

#5511 Improve variant reordering in variant edit page
  .changeset/sour-teachers-relax.md
  src/products/components/ProductVariantNavigation/ProductVariantNavigation.tsx
  src/products/components/ProductVariantNavigation/components/ProductVariantEmptyItem.tsx
  src/products/components/ProductVariantNavigation/components/ProductVariantItem.tsx
  src/products/components/ProductVariantNavigation/components/SortableContainer.tsx
  src/products/components/ProductVariantNavigation/hooks/useVariantDrag.test.ts
  src/products/components/ProductVariantNavigation/hooks/useVariantDrag.ts
  src/products/components/ProductVariantNavigation/types.ts
Labels: run pw-e2e

#5518 Fixes for some errors reported to Sentry
  .changeset/fuzzy-rockets-begin.md
  src/components/Locale/Locale.tsx
  src/navigation/components/MenuDetailsPage/tree.ts
  src/products/components/ProductVariants/datagrid.ts
  src/searches/useAttributeValueSearch.ts
Labels: run pw-e2e

#5519 add github actions for announcing releases and help-wanted issues
  .github/workflows/github-releases-to-discord.yml
  .github/workflows/help-wanted-issues-to-discord.yml
Labels: skip changeset

#5457 Assign specific items in voucher creation
  .changeset/tall-chefs-burn.md
  src/components/AssignAttributeValueDialog/AssignAttributeValueDialog.tsx
  src/components/AssignCategoryDialog/AssignCategoryDialog.tsx
  src/components/AssignCollectionDialog/AssignCollectionDialog.tsx
  src/components/AssignProductDialog/AssignProductDialog.tsx
  src/components/CountryList/CountryList.tsx
  src/components/CountryList/utils.test.ts
  src/components/CountryList/utils.ts
  src/discounts/components/DiscountCategories/DiscountCategories.tsx
  src/discounts/components/DiscountCollections/DiscountCollections.tsx
  src/discounts/components/DiscountCountrySelectDialog/DiscountCountrySelectDialog.tsx
  src/discounts/components/DiscountProducts/DiscountProducts.tsx
  src/discounts/components/DiscountRules/componenets/RuleForm/components/RuleConditionValues/hooks/options/mocks.ts
  src/discounts/components/SaleDetailsPage/SaleDetailsPage.tsx
  src/discounts/components/VoucherCreatePage/VoucherCreatePage.tsx
  src/discounts/components/VoucherCreatePage/const.ts
  src/discounts/components/VoucherCreatePage/hooks/useActiveTab.test.ts
  src/discounts/components/VoucherCreatePage/hooks/useActiveTab.ts
  src/discounts/components/VoucherCreatePage/hooks/useSpecificItemsAssign.test.ts
  src/discounts/components/VoucherCreatePage/hooks/useSpecificItemsAssign.ts
  src/discounts/components/VoucherCreatePage/hooks/useSpecificItemsPagination.test.ts
  src/discounts/components/VoucherCreatePage/hooks/useSpecificItemsPagination.ts
  src/discounts/components/VoucherCreatePage/types.ts
  src/discounts/components/VoucherCreatePage/utils.ts
  src/discounts/components/VoucherDetailsPage/VoucherDetailsPage.tsx
  src/discounts/components/VoucherValue/VoucherValue.tsx
  src/discounts/types.ts
  src/discounts/urls.ts
  src/discounts/views/SaleDetails/SaleDetails.tsx
  src/discounts/views/VoucherCreate/VoucherCreate.tsx
  src/discounts/views/VoucherCreate/handlers.test.ts
  src/discounts/views/VoucherCreate/handlers.ts
  src/discounts/views/VoucherDetails/VoucherDetails.tsx
  src/fragments/categories.ts
  src/fragments/collections.ts
  src/fragments/products.ts
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/searches/useCategorySearch.ts
  src/searches/useCollectionSearch.ts
  src/searches/useProductSearch.ts
  src/shipping/fixtures.ts
Labels: run pw-e2e

#5525 Rearrange extensions components
  src/extensions/views/ExploreExtensions/ExploreExtensions.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/ExtenionItem.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/ExtensionItem.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppActions/AppActions.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppActions/AppActions.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppActions/index.ts
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppInstallButton/AppInstallButton.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppInstallButton/AppInstallButton.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppInstallButton/index.ts
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/InstalledBadge.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/PluginActions.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/PluginWarning.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/hooks/useExtension.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/hooks/useExtension.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/index.ts
  src/extensions/views/ExploreExtensions/components/ExtensionsGroup.tsx
  src/extensions/views/ExploreExtensions/components/ExtensionsList/ExtensionsList.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtensionsList/ExtensionsList.tsx
  src/extensions/views/ExploreExtensions/components/ExtensionsList/LoadingSkeleton.tsx
  src/extensions/views/ExploreExtensions/components/ExtensionsList/index.ts
  src/extensions/views/ExploreExtensions/hooks/useAppStoreExtensions.test.ts
  src/extensions/views/ExploreExtensions/hooks/useAppStoreExtensions.ts
  src/extensions/views/ExploreExtensions/hooks/useExploreExtensions.test.ts
  src/extensions/views/ExploreExtensions/hooks/useExploreExtensions.ts
  src/extensions/views/ExploreExtensions/hooks/useExtenstionsFilter.test.tsx
  src/extensions/views/ExploreExtensions/hooks/useExtenstionsFilter.ts
  src/extensions/views/ExploreExtensions/index.ts
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/components/DeleteFailedInstallationDialog.tsx
  src/extensions/views/InstalledExtensions/components/FailedInstallationActions.tsx
  src/extensions/views/InstalledExtensions/components/InfoLabels/AppDisabledInfo.tsx
  src/extensions/views/InstalledExtensions/components/InfoLabels/FailedInstallationInfo.tsx
  src/extensions/views/InstalledExtensions/components/InfoLabels/FailedWebhookInfo.tsx
  src/extensions/views/InstalledExtensions/components/InfoLabels/InfoLabelsContainer.tsx
  src/extensions/views/InstalledExtensions/components/InfoLabels/InstallationPendingInfo.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton.tsx
  src/extensions/views/InstalledExtensions/hooks/useActiveAppsInstallations.ts
  src/extensions/views/InstalledExtensions/hooks/useInstallationNotify.ts
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.tsx
  src/extensions/views/InstalledExtensions/index.ts
Labels: run pw-e2e, skip changeset

#5528 InstalledExtensionsList test
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.test.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/index.ts
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.test.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/index.ts
  src/extensions/views/InstalledExtensions/hooks/useActiveAppsInstallations.test.ts
  src/extensions/views/InstalledExtensions/hooks/useActiveAppsInstallations.ts
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensionsFilter.test.ts
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensionsFilter.ts
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.test.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.tsx
Labels: run pw-e2e, skip changeset

#5531 Improvments for extensions installed list
  src/extensions/views/InstalledExtensions/components/InfoLabels/FailedWebhookInfo.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.test.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/LoadinSkeleton.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
Labels: run pw-e2e, skip changeset

#5526 Update messages for gift card list in Customer details
  .changeset/happy-eels-grin.md
  locale/defaultMessages.json
  src/giftCards/components/GiftCardCustomerCard/messages.ts
Labels: run pw-e2e

#5543 Add caching policies for extensions list
  .changeset/light-fireants-wave.md
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
  src/graphql/client.ts
Labels: run e2e, run pw-e2e

#5545 Fix extensions page not loading when user doesn't have MANAGE_APPS permission
  src/extensions/views/InstalledExtensions/hooks/useActiveAppsInstallations.ts
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.test.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.tsx
Labels: run pw-e2e, skip changeset

#5529 Installed extensions remove dev ff
  .changeset/tiny-rings-hang.md
  .featureFlags/extensions.md
  .featureFlags/generated.tsx
  playwright/pages/extensionsPage.ts
  playwright/tests/singlePermissions/readonlyExtensionsAccess.spec.ts
  src/extensions/index.tsx
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.test.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.tsx
Labels: run pw-e2e

#5546 Fix empty page in /extensions
  .changeset/quiet-icons-dress.md
  src/extensions/index.tsx
Labels: skip e2e

#5548 Fix SALEOR_119 and SALEOR_120 tests after release installed extensions
  playwright/pages/extensionsPage.ts
  playwright/tests/apps.spec.ts
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.test.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.tsx
Labels: run pw-e2e, skip changeset

#5550 Removing community live update baner
  .knip.json
  src/welcomePage/WelcomePageTilesContainer/WelcomePageTilesContainer.tsx
Labels: run pw-e2e, skip changeset

#5551 Allow downloads app frame
  .changeset/smart-suits-divide.md
  src/apps/components/AppFrame/AppIFrame.tsx
Labels: run e2e, run pw-e2e

#5522 New extensions install page
  .changeset/curly-pants-worry.md
  locale/defaultMessages.json
  package.json
  src/apps/components/AppAvatar/AppAvatar.tsx
  src/components/AppLayout/TopNav/Root.tsx
  src/components/AppLayout/TopNav/TopNavWrapper.tsx
  src/components/Card/Root.tsx
  src/components/HookFormInput/HookFormInput.tsx
  src/components/HookFormInput/index.ts
  src/components/InputWithPlaceholder/InputWithPlaceholder.module.css
  src/components/InputWithPlaceholder/InputWithPlaceholder.tsx
  src/cssModules.d.ts
  src/extensions/components/ExternalLinkUnstyled/ExternalLinkUnstyled.tsx
  src/extensions/components/ExternalLinkUnstyled/index.ts
  src/extensions/index.tsx
  src/extensions/messages.ts
  src/extensions/urls.ts
  src/extensions/utils.ts
  src/extensions/views/InstallCustomExtension/InstallCustomExtension.test.tsx
  src/extensions/views/InstallCustomExtension/InstallCustomExtension.tsx
  src/extensions/views/InstallCustomExtension/components/InstallExtensionManifestData/IconsSection.tsx
  src/extensions/views/InstallCustomExtension/components/InstallExtensionManifestData/InstallExtensionManifestData.tsx
  src/extensions/views/InstallCustomExtension/components/InstallExtensionManifestData/SaleorLogo.test.tsx
  src/extensions/views/InstallCustomExtension/components/InstallExtensionManifestData/SaleorLogo.tsx
  src/extensions/views/InstallCustomExtension/components/InstallExtensionManifestData/index.ts
  src/extensions/views/InstallCustomExtension/components/InstallSectionData/InstallSectionData.test.tsx
  src/extensions/views/InstallCustomExtension/components/InstallSectionData/InstallSectionData.tsx
  src/extensions/views/InstallCustomExtension/components/InstallSectionData/index.ts
  src/extensions/views/InstallCustomExtension/components/ManifestUrlForm/ManifestUrlForm.test.tsx
  src/extensions/views/InstallCustomExtension/components/ManifestUrlForm/ManifestUrlForm.tsx
  src/extensions/views/InstallCustomExtension/components/ManifestUrlForm/index.ts
  src/extensions/views/InstallCustomExtension/consts.ts
  src/extensions/views/InstallCustomExtension/hooks/useFetchManifest.test.ts
  src/extensions/views/InstallCustomExtension/hooks/useFetchManifest.ts
  src/extensions/views/InstallCustomExtension/hooks/useInstallApp.test.ts
  src/extensions/views/InstallCustomExtension/hooks/useInstallApp.ts
  src/extensions/views/InstallCustomExtension/hooks/useLoadQueryParamsToForm.test.ts
  src/extensions/views/InstallCustomExtension/hooks/useLoadQueryParamsToForm.ts
  src/extensions/views/InstallCustomExtension/hooks/useValidateUrl.test.ts
  src/extensions/views/InstallCustomExtension/hooks/useValidateUrl.ts
  src/extensions/views/InstallCustomExtension/index.ts
  src/extensions/views/InstallCustomExtension/types.ts
  src/links.ts
  src/utils/errors/app.ts
  src/utils/hook-form/auto-submit.test.tsx
  src/utils/hook-form/auto-submit.ts
  src/utils/ref.ts
Labels: run pw-e2e

#5533 Refactor Playwright test actions to remove Testmo integration
  .changeset/mighty-bottles-sleep.md
  .github/actions/run-pw-tests/action.yml
  .github/actions/testmo/testmo-finish/action.yml
  .github/actions/testmo/testmo-init/action.yml
  .github/actions/testmo/testmo-threads-submit-playwright/action.yml
  .github/workflows/package-lock.json
  .github/workflows/package.json
  .github/workflows/postTestsResults.js
  .github/workflows/pr-automation.yml
  .github/workflows/run-test-manual.yml
  .github/workflows/run-tests-on-release.yml
  .gitignore
  .knip.json
  package-lock.json
  package.json
  playwright.config.ts
Labels: run pw-e2e

#5541 Show custom apps and plugins on installed extensions
  src/custom-apps/components/CustomAppDetailsPage/CustomAppDetailsPage.tsx
  src/extensions/types.ts
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.test.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.tsx
  src/extensions/views/InstalledExtensions/components/ViewPluginDetails.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.test.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.tsx
  src/extensions/views/InstalledExtensions/utils.ts
  src/icons/PluginIcon.tsx
  src/icons/WebhookIcon.tsx
  src/plugins/components/PluginsDetailsPage/PluginsDetailsPage.tsx
Labels: run pw-e2e, skip changeset

#5559 Update `transactionId` type in refund mutation
  .changeset/large-panthers-repeat.md
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/orders/components/OrderGrantRefundPage/form.ts
  src/orders/components/OrderGrantRefundPage/utils.ts
  src/orders/components/OrderTransactionRefundPage/OrderTransactionRefundPage.tsx
  src/orders/components/OrderTransactionRefundPage/formDefaults.ts
  src/orders/mutations.ts
  src/orders/views/OrderGrantRefund/OrderGrantRefund.tsx
Labels: run pw-e2e

#5527 Add customer metadata filtering in Customer list
  .changeset/nice-months-wash.md
  src/components/ConditionalFilter/UI/MetadataInput.tsx
  src/components/ConditionalFilter/constants.ts
  src/components/ConditionalFilter/queryVariables.test.ts
  src/components/ConditionalFilter/queryVariables.ts
Labels: run pw-e2e

#5556 Improve error handling on add custom extension page
  locale/defaultMessages.json
  src/extensions/views/AddCustomExtension/AddCustomExtension.tsx
  src/extensions/views/AddCustomExtension/hooks/useHandleCreateAppSubmit.test.ts
  src/extensions/views/AddCustomExtension/hooks/useHandleCreateAppSubmit.ts
Labels: run pw-e2e, skip changeset

#5561 Update pagination UI
  .changeset/large-dragons-applaud.md
  src/components/TablePagination/TablePagination.test.tsx
  src/components/TablePagination/TablePagination.tsx
Labels: run pw-e2e

#5565 Copy views for managing plugins to `/extensions`
  .changeset/tricky-hats-divide.md
  src/extensions/index.tsx
  src/extensions/urls.ts
  src/extensions/views/EditPluginExtension/EditPluginExtension.test.ts
  src/extensions/views/EditPluginExtension/EditPluginExtension.tsx
  src/extensions/views/EditPluginExtension/components/PluginAuthorization.tsx
  src/extensions/views/EditPluginExtension/components/PluginDetailsChannelsCard/PluginDetailsChannelsCard.tsx
  src/extensions/views/EditPluginExtension/components/PluginDetailsChannelsCard/PluginDetailsChannelsCardContent.tsx
  src/extensions/views/EditPluginExtension/components/PluginDetailsChannelsCard/index.tsx
  src/extensions/views/EditPluginExtension/components/PluginDetailsChannelsCard/messages.ts
  src/extensions/views/EditPluginExtension/components/PluginInfo.tsx
  src/extensions/views/EditPluginExtension/components/PluginSecretFieldDialog.tsx
  src/extensions/views/EditPluginExtension/components/PluginSettings/PluginSettings.tsx
  src/extensions/views/EditPluginExtension/components/PluginSettings/index.ts
  src/extensions/views/EditPluginExtension/components/PluginSettings/styles.ts
  src/extensions/views/EditPluginExtension/components/PluginsDetailsPage.tsx
  src/extensions/views/EditPluginExtension/index.ts
  src/extensions/views/EditPluginExtension/utils.ts
  src/extensions/views/InstalledExtensions/components/ViewPluginDetails.tsx
Labels: run pw-e2e

#5544 Changing sidebar flow
  .changeset/stupid-masks-cheat.md
  locale/defaultMessages.json
  playwright/tests/navigation.spec.ts
  playwright/tests/singlePermissions/contentPage.spec.ts
  playwright/tests/singlePermissions/discount.spec.ts
  playwright/tests/singlePermissions/extensions.spec.ts
  playwright/tests/singlePermissions/orders.spec.ts
  playwright/tests/singlePermissions/product.spec.ts
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
  src/configuration/index.tsx
  src/icons/Modeling.tsx
  src/intl.ts
  src/navigation/components/MenuDetailsPage/MenuDetailsPage.tsx
  src/navigation/components/MenuItems/MenuItems.tsx
  src/navigation/components/MenuListPage/MenuListPage.tsx
  src/navigation/components/MenuProperties/MenuProperties.tsx
  src/pages/components/PageOrganizeContent/PageOrganizeContent.tsx
Labels: run pw-e2e
