Repository saleor/saleor-dashboard, pull requests merged in 2025-08, with the labels that each got.

#5749 Extract jest setup package json
  .knip.json
  jest.config.js
  lint-staged.config.js
  package-lock.json
  package.json
Labels: skip changeset

#5766 feat: add ESLint rule to deprecate Material-UI and Macaw-UI icons
  .eslintrc.json
  eslint-local-rules.js
  lint/rules/no-deprecated-icons.js
  src/icons/ArrowDropdown.tsx
  src/icons/ArrowSort.tsx
  src/icons/Attributes.tsx
  src/icons/Channels.tsx
  src/icons/Cloud.tsx
  src/icons/Configuration.tsx
  src/icons/Contents.tsx
  src/icons/Customers.tsx
  src/icons/Discounts.tsx
  src/icons/Drag.tsx
  src/icons/ErrorCircle.tsx
  src/icons/ErrorExclamationCircle.tsx
  src/icons/FullScreenIcon.tsx
  src/icons/Graphql.tsx
  src/icons/Home.tsx
  src/icons/Marketplace.tsx
  src/icons/Miscellaneous.tsx
  src/icons/Navigation.tsx
  src/icons/Orders.tsx
  src/icons/PageTypes.tsx
  src/icons/PermissionGroups.tsx
  src/icons/Plugins.tsx
  src/icons/ProductTypes.tsx
  src/icons/Products.tsx
  src/icons/ShippingMethods.tsx
  src/icons/SiteSettings.tsx
  src/icons/StaffMembers.tsx
  src/icons/Taxes.tsx
  src/icons/Translations.tsx
  src/icons/Trash.tsx
  src/icons/Warehouses.tsx
Labels: skip changeset

#5777 Remove Cypress leftovers in GitHub workflows, npm scripts
  .github/actions/get-env-vars/action.yml
  .github/workflows/run-tests-on-release.yml
  .github/workflows/testsHelpers/getEnvironmentVariables.js
  docs/running-tests.md
  package.json
  src/services/errorTracking/adapters/Sentry.ts
Labels: skip changeset

#5780 refactor: improve UnderlineLink component API and structure
  src/orders-v2/order-customer/order-customer-header.tsx
  src/orders-v2/order-header.tsx
  src/orders-v2/underline-link.tsx
Labels: skip changeset

#5783 Add additional section to order details sidebar
  locale/defaultMessages.json
  src/orders-v2/order-apps.tsx
  src/orders-v2/order-detail-page.tsx
  src/orders-v2/order-invoices.tsx
  src/orders-v2/order-model.test.ts
  src/orders-v2/order-model.ts
  src/orders-v2/order-notes.tsx
  src/orders-v2/storybook/fixtures.ts
  src/orders-v2/storybook/order-detail-page.stories.tsx
  src/orders-v2/storybook/order-invoices.stories.tsx
Labels: skip changeset

#5781 Remove auto pick workflow & selecting PW on release tests
  .github/workflows/auto-pick.yml
  .github/workflows/run-tests-on-release.yml
Labels: skip changeset

#5784 Restrict legacy packages
  eslint.config.mjs
Labels: skip changeset

#5786 Fix attribute filtering on Products list
  .changeset/fix-reference-attribute-filtering.md
  schema.graphql
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/AttributeQueryVarsBuilder.test.ts
  src/components/ConditionalFilter/FiltersQueryBuilder/queryVarsBuilders/AttributeQueryVarsBuilder.ts
  src/components/ConditionalFilter/queryVariables.test.ts
  src/graphql/fragmentTypes.generated.ts
  src/graphql/typePolicies.generated.ts
  src/graphql/types.generated.ts
Labels: run pw-e2e

#5798 Fix e2e
  playwright/pages/appInstallationPage.ts
  playwright/pages/productPage.ts
  playwright/tests/apps.spec.ts
  playwright/tests/discounts.spec.ts
  playwright/tests/product.spec.ts
  playwright/tests/singlePermissions/plugins.spec.ts
Labels: run pw-e2e, skip changeset

#5796 Add advanced CodeQL setup
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: skip changeset

#5804 Add CodeQL Advanced to 3.21 branch
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: skip changeset
