Repository saleor/saleor-dashboard, pull requests merged in 2025-05, with the labels that each got.

#5568 Update action buttons in lists and tables
  .changeset/stale-years-sparkle.md
  src/attributes/components/AttributeValues/AttributeValues.tsx
  src/channels/pages/ChannelsListPage/ChannelsListPage.tsx
  src/components/CountryList/CountryList.tsx
  src/components/IconButtonTableCell/IconButtonTableCell.tsx
  src/components/TablePagination/TablePaginationActions.tsx
  src/components/TablePagination/index.ts
  src/custom-apps/components/CustomAppDetailsPage/CustomAppDetailsPage.tsx
  src/custom-apps/components/CustomAppListPage/CustomAppListPage.tsx
  src/custom-apps/components/CustomAppTokens/CustomAppTokens.tsx
  src/custom-apps/components/WebhooksList/WebhooksList.tsx
  src/navigation/components/MenuItemsSortableTree/MenuItemsSortableTreeItem.tsx
  src/permissionGroups/components/PermissionGroupMemberList/PermissionGroupMemberList.tsx
  src/productTypes/components/ProductTypeAttributes/ProductTypeAttributes.tsx
  src/productTypes/views/ProductTypeList/ProductTypeList.tsx
  src/shipping/components/ShippingZoneRates/ShippingZoneRates.tsx
  src/warehouses/components/WarehouseList/WarehouseList.tsx
Labels: run pw-e2e

#5574 Align order-related buttons
  .changeset/mean-trains-shake.md
  src/orders/components/OrderDraftDetails/OrderDraftDetails.tsx
  src/orders/components/OrderFulfilledProductsCard/ActionButtons.tsx
  src/orders/components/OrderPayment/OrderPayment.tsx
  src/orders/components/OrderUnfulfilledProductsCard/OrderUnfulfilledProductsCard.tsx
Labels: run pw-e2e

#5558 Fix "Finalize" button in draft orders
  .changeset/cyan-shirts-relate.md
  src/orders/components/OrderDraftPage/OrderDraftPage.tsx
  src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
Labels: run pw-e2e

#5573 Warehouse radio group ui update
  .changeset/green-buckets-join.md
  locale/defaultMessages.json
  src/components/SimpleRadioGroupField.tsx
  src/index.css
  src/warehouses/components/WarehouseSettings/WarehouseSettings.tsx
  src/warehouses/components/WarehouseSettings/messages.ts
Labels: run pw-e2e

#5570 Update description about parsing permissions from graphql ast
  src/custom-apps/components/PermissionAlert/utils.ts
Labels: skip changeset, skip e2e

#5576 Set working directory in pipelines to workflows directory
  .changeset/red-crews-agree.md
  .github/actions/get-env-vars/action.yml
  .github/workflows/package-lock.json
  .github/workflows/run-tests-on-release.yml
Labels: run pw-e2e

#5578 Change "Orders" to "Fulfulment"
  .changeset/stale-avocados-applaud.md
  locale/defaultMessages.json
  src/apps/components/AppAlerts/AlertExclamationIcon.tsx
  src/apps/components/AppAlerts/SidebarAppAlert.test.tsx
  src/apps/components/AppAlerts/SidebarAppAlert.tsx
  src/apps/components/AppDetailsPage/messages.ts
  src/apps/components/AppWebhooksDisplay/AppWebhooksDisplay.tsx
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
  src/components/Sidebar/menu/types.ts
  src/icons/ExclamationIconFilled.tsx
  src/intl.ts
  src/orders/components/OrderDetailsPage/utils.test.tsx
  src/orders/components/OrderGrantRefundPage/messages.ts
  src/welcomePage/WelcomePageOnboarding/hooks/useOnboardingData.tsx
Labels: run pw-e2e

#5580 Fix extension menu highlight when visiting an app
  locale/defaultMessages.json
  src/components/Sidebar/menu/utils.ts
Labels: run pw-e2e, skip changeset

#5571 Add new navigation for Installed Extensions page
  locale/defaultMessages.json
  src/extensions/messages.ts
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/components/AddExtensionDropdown/AddExtensionDropdown.tsx
  src/extensions/views/InstalledExtensions/components/AddExtensionDropdown/index.ts
Labels: run pw-e2e, skip changeset

#5577 Update navigation on Explore Extensions page
  locale/defaultMessages.json
  src/extensions/components/ExploreExtensionsActions.tsx
  src/extensions/messages.ts
  src/extensions/views/ExploreExtensions/ExploreExtensions.tsx
  src/extensions/views/ExploreExtensions/components/ExploreExtensionsActions.test.tsx
  src/extensions/views/ExploreExtensions/components/ExploreExtensionsActions.tsx
Labels: run pw-e2e, skip changeset

#5563 Remove old views when new extensions are enabled
  src/configuration/ConfigurationPage.test.tsx
  src/configuration/ConfigurationPage.tsx
  src/configuration/index.tsx
  src/configuration/styles.ts
  src/configuration/types.ts
  src/custom-apps/index.tsx
Labels: run pw-e2e, skip changeset

#5585 Fix wrong feature flag used to hide navigation items
  src/configuration/index.tsx
Labels: run pw-e2e, skip changeset

#5560 Add slack reports
  .changeset/ten-dingos-bow.md
  .github/actions/flaky-tests-report/action.yml
  .github/workflows/pr-automation.yml
  playwright.config.ts
Labels: run pw-e2e

#5567 Update onboarding for extensions
  .changeset/soft-maps-provide.md
  locale/defaultMessages.json
  src/extensions/views/InstalledExtensions/InstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/welcomePage/WelcomePageOnboarding/WelcomePageOnboarding.test.tsx
  src/welcomePage/WelcomePageOnboarding/WelcomePageOnboarding.tsx
  src/welcomePage/WelcomePageOnboarding/components/WelcomePageWebhooksButton.tsx
  src/welcomePage/WelcomePageOnboarding/hooks/useOnboardingData.tsx
  src/welcomePage/WelcomePageOnboarding/mocks.ts
  src/welcomePage/WelcomePageOnboarding/onboardingContext/OnboardingContext.tsx
  src/welcomePage/WelcomePageOnboarding/onboardingContext/initialOnboardingState.ts
  src/welcomePage/WelcomePageOnboarding/onboardingContext/types.ts
  src/welcomePage/WelcomePageOnboarding/onboardingContext/useExpandedOnboardingId.test.ts
  src/welcomePage/WelcomePageOnboarding/onboardingContext/useExpandedOnboardingId.ts
  src/welcomePage/WelcomePageOnboarding/onboardingContext/utils.test.ts
  src/welcomePage/WelcomePageOnboarding/onboardingContext/utils.ts
Labels: run pw-e2e

#5586 Update sidebar navigation for extensions installed subviews
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
  src/components/Sidebar/menu/types.ts
  src/components/Sidebar/menu/utils.test.ts
  src/components/Sidebar/menu/utils.ts
  src/extensions/urls.ts
Labels: run pw-e2e, skip changeset

#5591 Fix sending null values when using dropdown attributes
  .changeset/stale-timers-remember.md
  src/attributes/utils/handlers.test.ts
  src/attributes/utils/handlers.ts
  src/hooks/useForm/index.ts
Labels: run pw-e2e

#5595 Fix: custom app details page not loading when user doesn't have manage_apps permissions
  locale/defaultMessages.json
  src/extensions/index.tsx
  src/extensions/messages.ts
  src/extensions/views/EditCustomExtension/EditCustomApp.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionDetailsPage/CustomExtensionDetailsPage.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionTokens/CustomExtensionTokens.tsx
  src/extensions/views/EditCustomExtension/components/WebhooksList/WebhooksList.tsx
Labels: run pw-e2e, skip changeset

#5594 Fix error on extensions list when user doesn't have manage_plugins
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
Labels: run pw-e2e, skip changeset

#5602 Change all references to page,content,page types to modeling-related
  locale/defaultMessages.json
  src/attributes/components/AttributeDetails/AttributeDetails.tsx
  src/components/AssignAttributeValueDialog/AssignAttributeValueDialog.tsx
  src/components/CardMenu/messages.ts
  src/components/ConditionalFilter/constants.ts
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
  src/configuration/index.tsx
  src/giftCards/GiftCardsList/messages.ts
  src/intl.ts
  src/navigation/components/MenuCreateDialog/MenuCreateDialog.tsx
  src/navigation/components/MenuItemDialog/MenuItemDialog.tsx
  src/navigation/components/MenuItemDialog/options.ts
  src/navigation/components/MenuItems/MenuItems.tsx
  src/navigation/components/MenuItemsSortableTree/MenuItemsSortableTree.tsx
  src/navigation/components/MenuList/MenuList.tsx
  src/navigation/views/MenuDetails/index.tsx
  src/navigation/views/MenuList/MenuList.tsx
  src/pageTypes/components/PageTypeAttributes/PageTypeAttributes.tsx
  src/pageTypes/components/PageTypeBulkDeleteDialog/PageTypeBulkDeleteDialog.tsx
  src/pageTypes/components/PageTypeCreatePage/PageTypeCreatePage.tsx
  src/pageTypes/components/PageTypeDetails/PageTypeDetails.tsx
  src/pageTypes/components/PageTypeDetailsPage/PageTypeDetailsPage.tsx
  src/pageTypes/components/PageTypeList/PageTypeList.tsx
  src/pageTypes/components/PageTypeListPage/PageTypeListPage.tsx
  src/pageTypes/hooks/usePageTypeDelete/messages.ts
  src/pageTypes/index.tsx
  src/pageTypes/views/PageTypeCreate.tsx
  src/pageTypes/views/PageTypeDetails.tsx
  src/pages/components/PageDetailsPage/messages.ts
  src/pages/components/PageListDatagrid/messages.ts
  src/pages/components/PageOrganizeContent/PageOrganizeContent.tsx
  src/pages/components/PageTypePickerDialog/messages.ts
  src/pages/views/PageList/filters.ts
  src/translations/components/TranslationsEntitiesListPage/TranslationsEntitiesListPage.tsx
  src/translations/components/TranslationsMenuItemPage/TranslationsMenuItemPage.tsx
  src/translations/components/TranslationsPagesPage/TranslationsPagesPage.tsx
Labels: run pw-e2e, skip changeset

#5605 Update e2e scenarios for modeling
  playwright/data/e2eTestData.ts
  playwright/pages/mainMenuPage.ts
  playwright/tests/singlePermissions/contentPage.spec.ts
  src/components/Sidebar/menu/hooks/useMenuStructure.tsx
Labels: run pw-e2e, skip changeset

#5607 Fix app installation flow when extensions are disabled
  playwright/data/url.ts
  playwright/pages/extensionsPage.ts
  playwright/tests/apps.spec.ts
  playwright/tests/staffMemberActivation.spec.ts
  src/extensions/views/InstalledExtensions/components/AddExtensionDropdown/AddExtensionDropdown.tsx
Labels: run pw-e2e, skip changeset

#5593 Product type details component UI update
  .changeset/nine-scissors-pull.md
  playwright/pages/productTypePage.ts
  src/productTypes/components/ProductTypeDetails/ProductTypeDetails.tsx
  src/productTypes/components/ProductTypeDetailsPage/ProductTypeDetailsPage.tsx
  src/productTypes/components/ProductTypeShipping/ProductTypeShipping.tsx
  src/productTypes/components/ProductTypeTaxes/ProductTypeTaxes.tsx
  src/productTypes/components/ProductTypeVariantAttributes/ProductTypeVariantAttributes.tsx
Labels: run pw-e2e

#5579 Unify components in transaction refund view
  .changeset/proud-jars-exist.md
  locale/defaultMessages.json
  src/components/QuantityInput.tsx
  src/orders/components/OrderCardTitle/OrderCardTitle.tsx
  src/orders/components/OrderFulfilledProductsCard/OrderFulfilledProductsCard.tsx
  src/orders/components/OrderFulfilledProductsCard/styles.ts
  src/orders/components/OrderPaymentSummaryCard/OrderPaymentSummaryCard.tsx
  src/orders/components/OrderRefund/OrderRefund.tsx
  src/orders/components/OrderRefundFulfilledProducts/OrderRefundFulfilledProducts.tsx
  src/orders/components/OrderRefundPage/OrderRefundPage.tsx
  src/orders/components/OrderRefundUnfulfilledProducts/OrderRefundUnfulfilledProducts.tsx
  src/orders/components/OrderReturnPage/OrderReturnPage.tsx
  src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/MaximalButton.tsx
  src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ReturnItemsCard.tsx
  src/orders/components/OrderReturnPage/components/MaximalButton.tsx
  src/orders/components/OrderReturnPage/components/PaymentSubmitCard/PaymentSubmitCard.tsx
  src/orders/components/OrderReturnPage/components/TransactionSubmitCard/TransactionSubmitCard.tsx
  src/orders/views/OrderRefund/OrderRefund.tsx
Labels: run pw-e2e

#5610 Update plugin extension details page
  .changeset/perfect-pens-decide.md
  locale/defaultMessages.json
  src/extensions/views/EditPluginExtension/EditPluginExtension.tsx
  src/extensions/views/EditPluginExtension/components/PluginAuthorization.tsx
  src/extensions/views/EditPluginExtension/components/PluginDetailsChannelsCard/PluginDetailsChannelsCardContent.tsx
  src/extensions/views/EditPluginExtension/components/PluginInfo.tsx
  src/extensions/views/EditPluginExtension/components/PluginSettings/PluginSettings.tsx
  src/extensions/views/EditPluginExtension/components/PluginsDetailsPage.tsx
  src/plugins/components/PluginAuthorization/PluginAuthorization.tsx
Labels: run pw-e2e

#5590 Update radio group UI in channel allocation
  .changeset/gold-lobsters-provide.md
  src/channels/components/ChannelAllocationStrategy/ChannelAllocationStrategy.tsx
  src/channels/components/ChannelAllocationStrategy/styles.ts
  src/extensions/views/EditCustomExtension/components/CustomExtensionDefaultToken/CustomExtensionDefaultToken.tsx
  src/index.css
Labels: run pw-e2e

#5584 Attributes properties form UI update
  .changeset/long-eggs-compare.md
  locale/defaultMessages.json
  playwright/tests/attributes.spec.ts
  src/attributes/components/AttributeDetails/AttributeDetails.tsx
  src/attributes/components/AttributeDetails/NumericUnits.tsx
  src/attributes/components/AttributeOrganization/AttributeOrganization.tsx
  src/attributes/components/AttributeProperties/AttributeProperties.tsx
  src/index.css
Labels: run pw-e2e

#5608 Reorganise model types view by using consistent layout
  .changeset/real-kings-listen.md
  locale/defaultMessages.json
  src/pageTypes/components/PageTypeAttributes/PageTypeAttributes.tsx
  src/pageTypes/components/PageTypeCreatePage/PageTypeCreatePage.tsx
  src/pageTypes/components/PageTypeDetailsPage/PageTypeDetailsPage.tsx
Labels: run pw-e2e

#5611 Show plugins in explore extensions when dev ff is enabled
  src/extensions/views/ExploreExtensions/hooks/useExploreExtensions.test.ts
  src/extensions/views/ExploreExtensions/hooks/useExploreExtensions.ts
Labels: run pw-e2e, skip changeset

#5612 Rows on extension lists are clickable
  locale/defaultMessages.json
  src/extensions/messages.ts
  src/extensions/types.ts
  src/extensions/views/InstalledExtensions/components/FailedInstallationActions.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.tsx
  src/extensions/views/InstalledExtensions/components/LoadinSkeleton.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.test.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/ViewDetailsActionButton.tsx
  src/extensions/views/InstalledExtensions/components/ViewDetailsActionButton/index.ts
  src/extensions/views/InstalledExtensions/components/ViewPluginDetails.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/hooks/usePendingInstallation.tsx
  src/icons/RetryIcon.tsx
Labels: run pw-e2e, skip changeset

#5618 Consistent layout across extensions view
  locale/defaultMessages.json
  src/extensions/messages.ts
  src/extensions/views/ExploreExtensions/ExploreExtensions.tsx
  src/extensions/views/ExploreExtensions/components/ExploreExtensionsActions.tsx
  src/extensions/views/InstalledExtensions/InstalledExtensions.test.tsx
  src/extensions/views/InstalledExtensions/InstalledExtensions.tsx
  src/extensions/views/InstalledExtensions/components/AddExtensionDropdown/AddExtensionDropdown.tsx
  src/links.ts
Labels: run pw-e2e, skip changeset

#5617 Improve copy button on create token modal
  .changeset/red-ladybugs-stare.md
  locale/defaultMessages.json
  src/extensions/views/EditCustomExtension/components/TokenCreateDialog/TokenCreateDialog.tsx
  src/extensions/views/EditCustomExtension/components/TokenCreateDialog/useClipboardCopy.ts
Labels: run pw-e2e

#5616 Minor extension ui improvements
  locale/defaultMessages.json
  src/apps/mutations.ts
  src/components/AccountPermissions/AccountPermissions.tsx
  src/components/AccountPermissions/components/PermissionList/PermissionList.tsx
  src/extensions/messages.ts
  src/extensions/utils.tsx
  src/extensions/views/EditCustomExtension/EditCustomApp.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionDetailsPage/CustomExtensionDetailsPage.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionTokens/CustomExtensionTokens.tsx
  src/extensions/views/EditCustomExtension/components/TokenCreateDialog/TokenCreateDialog.tsx
  src/extensions/views/EditManifestExtension/components/AppPermissionsDialog/AppPermissionsDialog.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/ExtensionItem.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/PluginActions.tsx
  src/extensions/views/InstallCustomExtension/components/InstallCustomExtensionFromUrl/InstallCustomExtensionFromUrl.tsx
  src/extensions/views/InstallCustomExtension/components/InstallTopNav.tsx
  src/graphql/hooks.generated.ts
  src/graphql/types.generated.ts
  src/utils/permissions.ts
Labels: run pw-e2e, skip changeset

#5620 Update link to docs for specific app install errors
  locale/defaultMessages.json
  src/extensions/messages.ts
  src/extensions/views/InstallCustomExtension/components/ManifestErrorMessage/ManifestErrorMessage.test.tsx
  src/extensions/views/InstallCustomExtension/components/ManifestErrorMessage/ManifestErrorMessage.tsx
  src/links.ts
Labels: skip changeset

#5621 Add build numer and url to slack results
  .github/actions/flaky-tests-report/action.yml
  .github/actions/run-pw-tests/action.yml
  .github/workflows/pr-automation.yml
  .github/workflows/run-test-manual.yml
  .github/workflows/run-tests-on-release.yml
Labels: skip changeset

#5624 Fix permission group e2e and staff activation tests
  .github/workflows/pr-automation.yml
  playwright/pages/permissionGroupDetailsPage.ts
  playwright/tests/orders.spec.ts
  playwright/tests/permissionGroup.spec.ts
  playwright/tests/staffMemberActivation.spec.ts
  playwright/tests/staffMembers.spec.ts
Labels: run pw-e2e, skip changeset

#5626 Fix local apps not linking to correct page when disabled
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.tsx
Labels: skip changeset

#5623 Extensions UI improvements
  locale/defaultMessages.json
  src/apps/components/AppDeactivateDialog/messages.ts
  src/extensions/components/AppActivateDialog/messages.ts
  src/extensions/components/AppDeactivateDialog/messages.ts
  src/extensions/components/AppDeleteDialog/AppDeleteDialog.test.tsx
  src/extensions/components/AppDeleteDialog/AppDeleteDialog.tsx
  src/extensions/components/AppDeleteDialog/index.ts
  src/extensions/components/AppDeleteDialog/messages.ts
  src/extensions/components/AppHeaderOptions.tsx
  src/extensions/messages.ts
  src/extensions/urls.ts
  src/extensions/views/AddCustomExtension/AddCustomExtension.test.tsx
  src/extensions/views/EditCustomExtension/EditCustomApp.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionDefaultToken/CustomExtensionDefaultToken.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionDetailsPage/CustomExtensionDetailsPage.tsx
  src/extensions/views/EditCustomExtension/components/CustomExtensionDetailsPage/styles.ts
  src/extensions/views/EditCustomExtension/components/CustomExtensionInformation/CustomExtensionInformation.tsx
  src/extensions/views/EditCustomExtension/components/TokenCreateDialog/useClipboardCopy.ts
  src/extensions/views/EditManifestExtension/AppManageView.tsx
  src/extensions/views/EditManifestExtension/components/AppDeleteDialog/messages.ts
  src/extensions/views/EditManifestExtension/components/AppDetailsPage/Header.tsx
  src/extensions/views/EditManifestExtension/components/AppDetailsPage/messages.ts
  src/extensions/views/EditManifestExtension/components/AppPermissionsDialog/messages.ts
  src/extensions/views/EditManifestExtension/components/AppWebhooksDisplay/AppWebhooksDisplay.tsx
  src/extensions/views/EditManifestExtension/messages.ts
  src/extensions/views/EditManifestExtensionPermissions/messages.ts
  src/extensions/views/EditPluginExtension/components/PluginsDetailsPage.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppActions/AppActions.test.tsx
  src/extensions/views/ExploreExtensions/components/ExtenionItem/components/AppActions/AppActions.tsx
  src/extensions/views/InstalledExtensions/components/InstalledExtensionsList/InstalledExtensionsList.test.tsx
  src/extensions/views/InstalledExtensions/hooks/useInstalledExtensions.test.tsx
  src/extensions/views/ViewManifestExtension/components/AppPage/message.ts
  src/giftCards/GiftCardUpdate/GiftCardUpdateInfoCard/messages.ts
  src/intl.ts
  src/orders/components/OrderMarkAsPaidDialog/OrderMarkAsPaidDialog.tsx
  src/utils/errors/transaction.ts
  src/welcomePage/WelcomePageOnboarding/hooks/useOnboardingData.tsx
Labels: run pw-e2e, skip changeset

#5628 SCL-934 - reconfigure dashboard workflows to use IAM roles instead of IAM users for CICD
  .github/workflows/deploy-and-run-cypress.yml
  .github/workflows/deploy-cloud.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-master-staging.yaml
  .github/workflows/deploy-staging-and-prepare-release.yaml
  .github/workflows/pr-automation.yml
  .github/workflows/test-env-cleanup.yml
Labels: skip changeset
